### ISSUE TITLE
Suddenly Bidirectional Sync? 

### ISSUE THREAD

**Issue by MadMakz** [nextcloud/android#10878]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When you set a folder for auto-sync it now not just syncs it to server but also back to local Android/media/com.nexcloud.client/>account< so you basicaly end up with doublicated files.

**Edit:** This also applies to manual Sync like "Send to" function! 

### Expected behaviour

Sync file to server. 

### Actual behaviour

Syncs file to server and local. 

### Android version

12

### Device brand and model

Samsung Galaxy A71

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

**Comment by luckkmaxx** [comment]
But you mean synced files are placed too in local nextcloud data folder, wich is a desired behavior when you select "original file will be..." > (keeped, deleted or) moved to nextcloud data folder.
So if thats not your case, you mean it happens altough you didnt choosed to move originals?

**Comment by natrius** [comment]
Just for me for clarification: We talk about "Auto-Upload" and not about "Sync"? Because there is simply no proper sync in Nextcloud Android. 

But yeah, sounds like you have the setting "Original file will be... 'kept in original folder' " activated as its default.

**Comment by markwyang** [comment]
I believe I am experiencing a very similar issue.

For the longest time I've had a custom sync setup from Android -> Remote folder for my Pixel 6a.  When tinkering with setting up another device last night, was noticing weird behaviors with how manual file uploads were causing many duplicate copies on the new phone S22+.  I went back to my Pixel 6a and noticed that for some reason my custom sync was NOW also syncing the files back down in the com.nextcloud.client directory even though it never happened before.

Thought it might have been a Nextcloud Hub 3 or Android app issue and low and behold, see that I'm not the only once experiencing this issue.  And as noticed, not all tasks were marked as complete before releasing..  This definitely seems to be a problem stemming from the most recent Android release.

**Comment by luckkmaxx** [comment]
Nextcloud app sometimes sucks! Maybe is useful for office files management but regarding media, there are much stable and feature rich apps that covers that aspect.
Photo gallery: https://play.google.com/store/apps/details?id=com.nkming.nc_photos (ad supported + paid apps, cheap it worth every cent)
Photo sync: Well, there are many options. What I know and sure are ones of the best are:
- Syncthing https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid
- Folder Sync (free and paid): https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite
Syncthing is great but FolderSync is more flexible and compatible with many cloud services.

What I miss in that apps is the ability to MOVE content from the source folder to another one in the phone. I choose Nextcloud app for media sync because moving files is my way to separate synced from new taken images keeping all I want in my device storage until I decide to delete it.

I think the release AS STABLE of 3.22 with hub3 support was an irresponsible mistake. Seems They were in a hurry to pull it off due to hub3 arrive. But as the app is, they should have released it as BETA.

**Comment by FALErwi** [comment]
I can confirm this bug, It doublicates my media twice.

**Comment by mikeeman** [comment]
+1 also having this problem and now I wake up to phone out of storage every day because a few larger videos are getting duplicated and duplicated over and over please fix

**Comment by AlvaroBrey** [comment]
This looks related to https://github.com/nextcloud/android/issues/10885 and as such will likely be fixed by #10914 as well

**Comment by davolesh** [comment]
Experiencing the same issue on Fold 4 and S22. Started after October 14th, 2022.

Files are being duplicated and stored to "/internal storage/Android/media/com.nextcloud.client/nextcloud/user@domain.name/"

**Comment by AlvaroBrey** [comment]
> Experiencing the same issue on Fold 4 and S22. Started after October 14th, 2022.
> 
> Files are being duplicated and stored to "/internal storage/Android/media/com.nextcloud.client/nextcloud/[user@domain.name](mailto:user@domain.name)/"

That is #10885 and will be fixed in 3.22.3, releasing next week.

**Comment by kanunnikau** [comment]
> > Experiencing the same issue on Fold 4 and S22. Started after October 14th, 2022.
> > Files are being duplicated and stored to "/internal storage/Android/media/com.nextcloud.client/nextcloud/[user@domain.name](mailto:user@domain.name)/"
> 
> That is #10885 and will be fixed in 3.22.3, releasing next week.

I have 3.22.3 and the issue seems to still be present. Android happily reports "app storage used: 13.81GB" (  
![Screenshot_2022-11-07-13-39-50-340_com miui securitycenter](https://user-images.githubusercontent.com/2588408/200315223-fb517fc4-2714-4050-b026-54da86814f30.jpg)
) and I definitely haven't synced that much stuff back to my phone.
What's more scary is that it's completely unclear how are things synced. What's going to be kept? What will be deleted?
I have a "Backups" folder on my phone that ideally should work as a one-way sync. Back things up on Android, see them safely on my server, clear folder on mobile to have space. Well, now I am seeing them also in the Nextcloud folder (Android/media/com.nextcloud.client/...). At least the app tells you via notification that it's downloading the unwanted files (if you happen to look at the moment).
Still I have no idea how to properly get rid of extra files on the phone. They do show up in the "on device" menu — and then what? Can I delete them only locally? Or is that "delete" command going to delete them on the server too?
So far I've noticed that if I just go to the app folder (Android/media/com.nextcloud.client/...) in a file manager and manually remove the duplicate files then things will be as desired — only on the server. But probably it's only temporary and the app will redownload them again at some point.
Also I've suddenly noticed that there *is* some limited two-way sync. Files downloaded to the app folder (Android/media/com.nextcloud.client/...) can be edited locally and the changes *will* upload to the server. That's quite cool.
But the duplicated upload/download is quite a pain in the a**. I suspect that it has drained my mobile account as at night the app was using flaky wifi to upload backup and photos. And when the wifi dropped the app just continued syncing everything down via mobile data. Not too cool. (I've reported this as #11002 ).

**Comment by davolesh** [comment]
On 3.22.3 as well, issue still persists. Nextcloud is successfully backing pictures up, but also moving the to the "synced" local folder on my phone.
![Screenshot_20221107_080218_Nextcloud](https://user-images.githubusercontent.com/10506816/200317023-7e21416e-4473-4909-8947-3075f13773f5.jpg)
![Screenshot_20221107_080340_Gallery](https://user-images.githubusercontent.com/10506816/200317239-406df228-728a-463a-a81b-114c7c65a775.jpg)

That folder is not set up to sync to my phone.

**Comment by joshtrichards** [comment]
Fixed in #10914 
Released in v3.23.0
