### ISSUE TITLE
Intermittent spurious "sync conflicts" on auto-upload

### ISSUE THREAD

**Issue by mnalis** [nextcloud/android#11906]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. have auto-upload of pictures enabled
2. take pictures
3. wait for auto upload
4. only sometimes (relatively rarely, i.e. every several months / few time a year in my case; but note that I take pictures only about once-a-week) auto upload will stop with **spurious** "sync conflict" notifications

### Expected behaviour

There should be no erroneous "sync conflicts", and picture should be uploaded normally, like it does in other 95%+ of the cases. 

### Actual behaviour

sync conflict shows:

![small_Screenshot_20230802_214133_com nextcloud client](https://github.com/nextcloud/android/assets/156656/27029e61-753f-4c5f-8f4f-07c7f703650f) ![small_Screenshot_20230802_214122_com nextcloud client](https://github.com/nextcloud/android/assets/156656/cfb8ed44-f9cd-4f75-838b-15e1aa15a71d)

and user has to manually resolve conflict (that in reality never [should have] happened)

### Android version

Android 10 (EMUI 12.0.0)

### Device brand and model

Huawei P30Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0 (f-droid)

### Nextcloud server version

Nextcloud Hub 3 (25.0.9)

### Using a reverse proxy?

No

### Android logs

[logcatOutput_1239.txt](https://github.com/nextcloud/android/files/12358425/logcatOutput_1239.txt)

### Server error logs

```bash
{"reqId":"P3kBokDqWRJFKWpEC6QD","level":0,"time":"2023-08-16T10:35:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21396","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 404","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 404","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 404 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 657","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 659","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 660","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 660","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 660 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 661","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 661","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 661 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 662","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 663","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 663","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"DeleteOrphanedItems","method":"","url":"--","message":"0 orphaned system tag relations deleted","userAgent":"--","version":"25.0.9.2","data":{"app":"DeleteOrphanedItems"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"DeleteOrphanedItems","method":"","url":"--","message":"0 orphaned user tag relations deleted","userAgent":"--","version":"25.0.9.2","data":{"app":"DeleteOrphanedItems"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"DeleteOrphanedItems","method":"","url":"--","message":"0 orphaned comments deleted","userAgent":"--","version":"25.0.9.2","data":{"app":"DeleteOrphanedItems"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"DeleteOrphanedItems","method":"","url":"--","message":"0 orphaned comment read marks deleted","userAgent":"--","version":"25.0.9.2","data":{"app":"DeleteOrphanedItems"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 663 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 668","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 670","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 671","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 675","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 682","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Log\\Rotate job with ID 682","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Log\\Rotate job with ID 682 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 683","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Preview\\BackgroundCleanupJob job with ID 683","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Preview\\BackgroundCleanupJob job with ID 683 in 1 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 684","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 685","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\DAV\\BackgroundJob\\UpdateCalendarResourcesRoomsBackgroundJob job with ID 685","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\DAV\\BackgroundJob\\UpdateCalendarResourcesRoomsBackgroundJob job with ID 685 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 686","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 687","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 689","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 753","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 753","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 753 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 759","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Core\\BackgroundJobs\\CleanupLoginFlowV2 job with ID 759","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Core\\BackgroundJobs\\CleanupLoginFlowV2 job with ID 759 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 873","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 873","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"0 reminders to process","userAgent":"--","version":"25.0.9.2","data":{"app":"dav"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 873 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 874","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Text\\Cron\\Cleanup job with ID 874","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"text","method":"","url":"--","message":"Run cleanup job for text sessions","userAgent":"--","version":"25.0.9.2","data":{"app":"text"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"text","method":"","url":"--","message":"Removed 0 inactive sessions","userAgent":"--","version":"25.0.9.2","data":{"app":"text"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Text\\Cron\\Cleanup job with ID 874 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 880","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 882","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 11647","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12196","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12304","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Activity\\BackgroundJob\\DigestMail job with ID 12304","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Activity\\BackgroundJob\\DigestMail job with ID 12304 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12306","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 12306","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 12306 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12685","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Bookmarks\\BackgroundJobs\\CrawlJob job with ID 12685","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Bookmarks\\BackgroundJobs\\CrawlJob job with ID 12685 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12686","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 15513","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 15587","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 15591","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 15593","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Circles\\Cron\\Maintenance job with ID 15593","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (3)","userAgent":"--","version":"25.0.9.2","data":{"app":""}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (2)","userAgent":"--","version":"25.0.9.2","data":{"app":""}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (1)","userAgent":"--","version":"25.0.9.2","data":{"app":""}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Circles\\Cron\\Maintenance job with ID 15593 in 1 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21040","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Bookmarks\\BackgroundJobs\\BackupJob job with ID 21040","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Bookmarks\\BackgroundJobs\\BackupJob job with ID 21040 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21045","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21046","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 21046","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 21046 in 0 seconds","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21393","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
{"reqId":"cmJDMyuh6AUzbe9Xw0hF","level":0,"time":"2023-08-16T10:40:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21396","userAgent":"--","version":"25.0.9.2","data":{"app":"cron"}}
```

### Additional information

In majority of the cases, picture was just taken (also, I do not use google or any other syncing of pictures, that is the only phone that sync to that account, and nobody else is interacting with that nextcloud account (e.g. via web etc.) at the time of error.

But note that **sometimes** (but much more rarely) the conflict will show for much older files (see left picture above, like 1 year+ old files `SVID_2022*` !) which were previously auto-uploaded just fine and nothing was complaining until the nextcloud app decided to throw a fit.

Guess: It seems like the app correctly uploads the picture, but then either does not receive confirmation that picture was successfully uploaded, or it does receive it (more likely) but then somehow forgets that and tries to upload it again and get surprised the file is already there. It might be related to intermittent Internet connect too (problem with error handling?)

The issue has happened sporadically for many months (years?) now with several different versions, but I can remember a time many years ago when the app worked just fine without that problem for years. Unfortunately I cannot specify more precisely when that was.

There are somewhat similar issues like https://github.com/nextcloud/android/issues/7905, https://github.com/nextcloud/android/issues/10628, https://github.com/nextcloud/android/issues/6938 etc.,  but some are autoclosed due to inactivity, I can actually get rid of the notification by choosing either of options (it is just a problem that this "conflict resolution" erroneously appears when there is no reason for it to happen at all), I'm not always uploading particularly big files (i.e. it happens with regular sized ~2-10MB pictures, while it works without problems on much bigger videos), and supposed fixes have not fixed it for me.

**Comment by Frank1967** [comment]
Hi, I have exactly the same problem with NC 26 and an Samsung S21FE phone, I even posted a message on the forum (but nobody replied): [https://help.nextcloud.com/t/android-nextcloud-app-automatic-uploads-and-synchronization-conflicts/167043](https://help.nextcloud.com/t/android-nextcloud-app-automatic-uploads-and-synchronization-conflicts/167043)

Question (which might help with debugging). Do you have enabled the upload only when connected to wifi and does this typical occur when you take photos while not being connected to wifi? I think I have seen a pattern here. Direct uploads while connecting to wifi no problem for me, photos taking offline and then being uploaded when becoming online: sync problem.

**Comment by mnalis** [comment]
> Do you have enabled the upload only when connected to wifi

Yes. `Only upload on unmetered Wi-Fi`, `Also upload existing files` and `Use subfolders` are all checked. Only upload when charging isn't.

> does this typical occur when you take photos while not being connected to wifi?

Hard to say. Last time this happened, I was definitively in area when I could've had wifi signal in one moment, but not on the other, then again have it etc.

> photos taking offline and then being uploaded when becoming online: sync problem.

I could give it a try in a week or two when I find some wifi, but I think it would happen more often to me if that was enough to reproduce the problem 100% of the times. Can you **_always_** reproduce it when you try it that way?

**Comment by Frank1967** [comment]
> I could give it a try in a week or two when I find some wifi, but I think it would happen more often to me if that was enough to reproduce the problem 100% of the times. Can you **_always_** reproduce it when you try it that way?

Well I'm >95% sure that this happens only when making a picture when I'm not in WIFI range, and that this issue occurs (for some images) when I'm in WIFI range again. So, not  100% sure that this **always** the case, therefore I asked you if you could confirm it :-), in the hope this gives some insight for the developers.

**Comment by cnaumer** [comment]
I have the same issue with two phones. It happens very often that those errors pop up. Also the server is marked as unreachable in the App. However, uploads work and I can browse files and download files. If I can help with debugging this let me know.

**Comment by TheBlusky** [comment]
Same issue. It's been years. I host my NC instance in my LAN, so I cannot upload when not at home on WiFi.
Not a clue how to workaround it.

**Comment by gionag** [comment]
+1

**Comment by MarcSeebold** [comment]
Same here.
As a fix/work around, can't the Android app check the md5 of both files and auto-resolve conflicts if they have the same?

**Comment by Ravadosh** [comment]
Same issue here, the problem only seems to be happening with phone clients, a few family users, all reporting the same issue on their phones, yet newly taken pictures still upload fine..

I myself sync between my phone, laptop and desktop machine, only the phones are affected, which makes me suspect a recent update on the phone clients that must have caused this.

**Comment by anibyl** [comment]
I have 49 notifications about sync conflicts all the time, between files that are identical. When I resolve one, which is 5 clicks, another one appears the moment I synchronisation starts again. Very annoying.

I initiated the upload with a few months of photos (including existing ones), and after an hour or so I started getting these notifications. So pretty much right away.

Android 13
Google Pixel 6
Graphene OS
App 3.26.0 (Google Play)
Nextcloud Hub 27.0.2 (OwnCube)

**Comment by gustavohw** [comment]
Same issue. +1

Android 13
Samsung S20FE
App 3.26.0 Google Play
Nextcloud Hub 27.1.1

**Comment by mnalis** [comment]
@gionag , @gustavohw and everyone else interested in resolving this issue: please click on :+1: icon at the bottom of first post if you intend to give it `+1`; otherwise the issue does not show to project owners as popular/important one.

**Comment by miblo69** [comment]
+1 

I have exactly the same issue, and have had for months/years. Plus the NC App seems to drain my phone battery when attempting to re-upload files that are in conflict.

**Comment by anibyl** [comment]
Funny thing, I built and installed this app on my phone, and the debug build **doesn't** have this issue. `master` branch. I've been using it for over a week now.

However, I didn't find any recent changes in related code. I'm thinking the conflicts don't occur not because the bug is fixed, but rather because of unknown circumstances (maybe enabling photo and video uploads at the same time? something else?).

**Comment by ptandler** [comment]
Had an issue which might be this one or quite similar: After an initial upload of the pictures folder containing about 2000 pictures (with the option to keep the pictures in place), the app detects all uploaded pictures again as new files and tries to upload them _again_ - but of course, the pictures now exist on the server and for all 2000 files we got a notification about the upload conflict... With this number of files, this is really unusable!

> Same here. As a fix/work around, can't the Android app check the md5 of both files and auto-resolve conflicts if they have the same? Or at least an option to bulk resolve the conflicts, e.g., "keep all local".

I really suggest that the upload uses some kind of hash in case of conflicts (in addition to file size ~~and maybe also timestamp~~) to check if the existing file is identical to the one to be uploaded. This would definitively help in reducing unnecessary upload warnings and dramatically improve UX!

**Comment by mnalis** [comment]
Have people tried workaround of going to `Settings` / `Auto upload` / three-vertial-dots / `Configure` / scroll to the bottom / `What to do if the file already exists?` and choose `Skip uploading` (or `Overwrite remote version`) instead of `Ask me every time` (which is default)?

If you already experience the problem, you might need to uninstall and then reinstall the app before setting autoupload folders with that options, as it seems that those options only apply to _new conflicts_, so everything already detected as conflict would keep showing popups no matter what.

I did that (uninstall & install again, and set it to `Skip uploading` on each and every folder), and it seems to not ask me again so far. Ugly workaround :crying_cat_face:, but hopefully will save stress in the long run...

**Comment by poltpolt** [comment]
i uninstalled the app, cleared data, reinstalled, set autoupload with "Skip uploading" but i still get conflict notification for some files  .... other from the same folder work fine receiving "skipping as the file exists"

**Comment by Sentyabrio** [comment]
same
