### ISSUE TITLE
[NOTICE] Version 3.30.1 Causing Sync Issues / Synchronising All Files

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/android#13872]
# Nextcloud Android Client Version 3.30.1
Dear Community,

It is with great regret that we have to inform you that a recent version of the Nextcloud Android Client, specifically version 3.30.1, has introduced a bug that may cause one or more of the following issues:
- increased battery usage and device temperature,
- increased mobile and non-mobile data usage,
- increased storage usage, and
- synchronisation of files not previously selected for synchronisation.

## Updating
We have carefully investigated this issue and released new versions which aim to address these issues. The first version to contain these changes is 3.30.2. Version 3.30.3 includes additional improvements. Both versions are available for download from [GitHub](https://github.com/nextcloud/android/releases).

The new versions include an additional check to stop unwanted background synchronisation. There is also an option to quickly check and stop two-way synchronisation for specific folders. To access this menu open *Settings* → *Internal two way sync*. On the following screen you will see all folders scheduled for two-way synchronisation and have the option to remove selected folders using the **×** icon next to the folder name.

![Two-Way Sync Settings](https://github.com/user-attachments/assets/dd271b01-95d0-4bf2-a89c-435792de6f01)

Unfortunately, the [F-Droid](https://f-droid.org/packages/com.nextcloud.client/) and [Google Play](https://play.google.com/store/apps/details?id=com.nextcloud.client) releases will take some more time to become available as they require additional verification and review.

We will update this issue as soon as the releases are available.

## Mitigation
First and foremost we recommend updating to version 3.30.2 or later using your preferred method. If this version is not available for you, or if something else is blocking this update, there are several options to mitigate any unwanted behaviour.

The simplest option is to reinstall the Nextcloud Android Client. Due to the technical nature of the issue reinstalling any version above 3.30.0 will resolve the issue. The process of reinstalling an app varies from Android version to Android version. However, the general process will be similar to the following:
1. Close any open app and open the app drawer
2. Press and hold on the Nextcloud app
3. Select App info
4. Select Uninstall
5. Confirm with Ok
6. Open App Centre of choice
	- Depending on your vendor, this will have different names, such as *Google Play Store*, *App Gallery*, *F-Droid*, etc.
7. Download and install Nextcloud Android Client

Please note that any local data of the Nextcloud Android Client that is present on the mobile device will be lost during the removal process.

### Enabling Data Limit and Warning
Many mobile network operators charge their subscribers an additional fee when they exceed their data allowance. To avoid these charges, most versions of Android offer some kind of safety measures. These include a Data Limit and Data Warning. The latter notifies you once the specified amount of mobile data has been used up. The former allows you to set a hard limit after which Android will disable mobile data and prevent you from using any more. Also note that you will *not* be able to use *any* apps that require an active data connection, such as Internet messengers.

Settings to enable and configure the Data Limit and Warnings can usually be found in the device settings.
1. Open Settings app
2. Select Network and Internet
3. Select Internet
4. Select ⚙ next to your mobile (data) carrier
5. Select Data warning and Data limit

## Technical Background
*Detailed technical information to be added shortly.*

## Related Issues
- #13738

**Comment by noci2012** [comment]
The github versions don't install on devices that install from F-Droid / Gplay / ?.

Older versions 3.29.1 available as APK on F-Droid does NOT install citing invalid package ....
So without uninstall no remedy.?

**Comment by ZetaTom** [comment]
@noci2012, F-Droid builds are signed by F-Droid. Builds published on GitHub are signed using our key. This means that one must, unfortunately, choose and stay with one source for continued updates.

In some cases, the versions differ in some aspects due to some other constraints, e.g. Google Libraries. This is the case for Google Play and F-Droid builds.

Downgrading is not officially supported, as far as I'm aware. To install an older version, one should first remove the newer one.

**Comment by bessman** [comment]
> Technical Background

I'm curious why the same files were repeatedly synchronized ad infinitum? I don't think the Technical Background currently addresses this.

In my case, Nextcloud downloaded 15 GB of data from a server containing 1 GB of data. Others have reported the same.

**Comment by zukunft** [comment]
I see in the F-Droid build log: 

com.nextcloud.client:30300290 2024-10-22 15:20:18,028 INFO: Building version 3.30.2 (30300290) of com.nextcloud.client .
...
BUILD SUCCESSFUL in 13m 56s 56 actionable tasks: 56 executed 2024-10-22 15:36:53,598 

It seems that it takes 3 to 4 days until the build is distributed. Maybe we should help F-Droid to speed up the distribution process. I some knows more, please help out.

**Comment by zukunft** [comment]
> I'm curious why the same files were repeatedly synchronized ad infinitum? 

I don't think so, because I have version 3.30.1 at the moment on LineageOS and it sync all files once (using almost all the battery), but at the moment it is fine. I checked it on another phone and it seems, that it sync the same file several times, but not ad infinitum. (Just my personal experience with 3 clients, so nothing to really relay on)

**Comment by szotsaki** [comment]
Mitigation (i.e. reinstall, but explained really verbosely) is for technical users only.

Many users don't know their password or _what_ a password is (an example from my circles where they just want to see pictures by swiping). For them re-logging into the app via a computer with a QR code through an obscure web UI path is impossible.

You littered every single user's phone with gigabytes of difficult-to-remove data. This is a major mess. Especially, that is comes just months after [another major synchronisation problem](https://github.com/nextcloud/android/issues/11974).

I already received complaints that Nextcloud duplicates all files into its cache and filling up the phone eventually (details in https://github.com/nextcloud/android/issues/13400#issuecomment-2408032978).

Please, create a proper, **automated** solution for this problem ASAP. Otherwise you offload solving this chaos to every single technical user who chose and distributed your application.

**Comment by tobiasKaminsky** [comment]
> You littered every single user's phone with gigabytes of difficult-to-remove data.

Data can be simply removed via "on device" and then removing the folder that you do not want, choosing "local only".

 

> Please, create a proper, **automated** solution for this problem ASAP.

I am all for it, but do you have an idea how?
Internally the synced folders are stored in a database and we cannot differentiate between wanted and wrongly added folders there.
This is why the new overview allows user to also cancel 2way sync, but only manually.

**Comment by szotsaki** [comment]
In the short term an "Empty local storage" button would be a good interim solution. I can communicate to press this button and this problem goes away. This would also conveniently fix https://github.com/nextcloud/android/issues/9128, too.

As a next step I could imagine a Trashbin-like system which, after a configurable amount of used local storage (e.g. 2% of device storage), it'd warn the user to press this button.

One more step further, the application could be re-architected in a way that it outsources the internal storage handling into a regular Linux directory which the user can manage themselves. This would fix https://github.com/nextcloud/android/issues/13400. Even if you agree with this direction, I see this would have many edge cases and is not a quick solution.

**Comment by Alifoss** [comment]
https://github.com/nextcloud/android/issues/13738#issuecomment-2438848193

**Comment by mase76** [comment]
Even when not in Wifi, 3.30.2 is syncing the same files over and over again, eating my monthly mobile data completely within a few hours. Removing the files from the sync did not stop it. I had to delete the file database to stop the sync. The app seems to be completely broken now.

**Comment by timkrief** [comment]
Hi, I just updated to 3.30.2 from f-droid and I saw "check listed folders in settings -> internal two sync", so I went and checked, the app took a really long time and then showed me a list of a LOT of folders, I could swipe for minutes. It says "Pas encore, bientôt synchronisé" (my app is in French, it means, "not yet, soon synchronized") for each folder. I don't know what that means, I don't know when it will do that and how to avoid it. I tried to press on the cross but it just make the app not responding and the time it would take to press that cross for each folder even if it was working would be insane. 

I'm scared by the idea of a two way sync being triggered on data I never wanted to two way sync. Apart from the issue of my phone storage being filled, my data is important and I don't want data from my phone to corrupt data on my server. I never selected those folders and I hope they won't sync, but I don't know what  "not yet, soon synchronized" means.

What should we do? Is there a way to prevent the app from attempting any sync for the time being, so that the issue can be fixed? I like being able to sync my photos to nextcloud and being able to sync some files manually, but I didn't know auto two way sync was a thing on android, is there a way to disable automatic two way sync?

**Comment by timkrief** [comment]
@ltguillaume I finally did it and I'm in the process of re-syncing all the files that were (intentionally) synced before. It reveals a lot of flaws with the sync system altogether, but it's not related to this issue. I'm still settings things up, but it seems to work for the time being, the issue of having all the folders added to two way sync is not happening anymore, but if I do add things to the two way sync system, they will sync again and again even with no modification, so I do have to make sure there's nothing in the two way sync page.

I would like to say that when going to the "two way sync" settings to see if there is no issue, it's quite troubling to have a completely blank screen. When I had the issue, I had a blank screen for a minute before all 15000 folders appeared in the list, so I couldn't tell easily if the issue was still there or if everything was fine. Many user go to that screen and think this is a bug. I think it should be a priority to add at least a single line "no two way sync folder yet" or something to make sure the experience is smooth. see for instance: 
[#13738](https://github.com/nextcloud/android/issues/13738#issuecomment-2440123933)

and:
> This is especially confusing because the fix notes for recent critical bugs explicitly say to check the two way sync configuration, so many users like me are being directed to this screen for the first time.  

 _Originally posted by @danepowell in [#13693](https://github.com/nextcloud/android/issues/13693#issuecomment-2439702362)_

**Comment by mase76** [comment]
The sync of the same files over and over again completely ate my monthly mobile data quota. Yes, we have a quota in Germany.
![Image](https://github.com/user-attachments/assets/ba4bd478-a580-40bb-8c71-c915ac24f6bc)

**Comment by AHeinlein** [comment]
I have been following this issue for some time now. Fortunately I read about it before the automatic upgrade from F-Droid triggered, so I am now still at 3.29.1 and waiting until it is safe to upgrade. But I am confused whether this is already the case (or will be once 3.30.3 hits the F-Droid store). Has anybody tested if the upgrade now works as intended, or are we assuming everyone has already been hit?

**Comment by Zocker1999NET** [comment]
To the Nextcloud developers, with all the information I have, this bug is/was essentially a Denial of Service "attack" across most users of Nextcloud Android. A bug can happen, as a dev myself I have full understanding how that can happen. But IMO, the correct response to a bug with this severity is to disable this feature fully, temporarily, for all users by **immediately rolling back to 3.29.1**.

Why do I consider this bug a servere Denial of Service:
- after an probably automatic app update, the app syncs all files, by itself & against the will of most users
- filling up the storage of the users on their phone, making them potentially unusable
- using a huge amount resources on Android
  - in my case comparable to running a 3D game, but in the background
  - using up valuable battery
  - creating a large amount of lag & heat visible to the user
- using up valuable data from cellular data plans
  - effectively taking the ability to use cellular data for other purposes 
  - sometimes directly incurring costs to because of "features" like "Datenautomatik" (after using up your data plan, you will automatically get 100 MiB extra for *just* 5 €, up to three times, before the data usage is limited to 350 kbit/s)
- given that, so far as I understand this bug, seems able to affect all users of the app, without further restrictions, a huge amount of users might be affected
  - in the context of an organization using Nextcloud, this will overload the IT support

So this necessarily includes a large amount of "normal" users which (like others stated before):
- will probably not no what happens to their phone
- will probably just remove Nextcloud from their phones (if they are able to detect it as the culprit)
- will most probably not read any of the mitigations which were, at least now & to my knowledge, only communicated through GitHub ("normal" users should not required to use GitHub)
- even so, they might not be able (or willing) to execute those mitigation steps you posted

And I know, these upcoming points are not something you could change, but are still true:
- most Nextcloud Android installations are from an app store (Google Play, F-Droid, …) with automatic updates enabled
- administrators of Nextcloud instances have, at least in many cases, no way of controlling the Nextcloud Android app version their users are using
  - (ignoring cases where users use their private phones instead of provided MDM-phones)

And new reports seem to suggest  that this new internal feature can still cause issues even through it is expected to be fixed. This brings me to the conclusion that IMO, for now, there is one thing to do now, *before trying to fix this bug*: **ASAP release a new version based on 3.29.1 (before 2way sync)** with a **notification explaining to "normal" users what happened & (if so) what they need to do now** (can of course link to this GH issue for the occasional nerd).

Also, but this can be deferred, it would be nice if a next version could delete the files the app created while syncing. However, I can understand that this might be a problematic step to take if users might have modified those files in the mean time.

(For clarification: I suggest reactions with 👍/👎 are referring to the idea of the immediate roll back to 3.29.1 & not for other points I made, so this can be used as a poll.)

**Comment by Zocker1999NET** [comment]
> Disabling it completely and then evaluating the current implementation yes. Rolling back to a previous version is not possible with Android, but they could have rolled back the entire implementation of two way sync to prevent the issues that occurred even after the "fixed" version.

If I understand you correctly, then we are on the same page here. I know that Android does not allow users to install an older Android version, that’s why my suggestion is, simplified: "take the code from 3.29.1, increase version number to 3.30.X, compile & publish". Sorry if this was unclear.

**Comment by timkrief** [comment]
I think we just need two buttons: 
- Remove all two way sync 
- Stop / Resume two way sync

The fact that I had 3.30.2 but I had no way of using my phone with internet access without nextcloud trying to sync everything is troubling. I had netguard blocking network for it, I had it as restrained battery wise I had it toggled as a samsung deep sleep app, and I was smashing the force stop button in the settings but it was still coming back trying to sync 15000 items.

Reinstalling as a mitigation is bad even for "pro" users, but people using nextcloud that are not maintainer had no idea of what was going on and wouldn't be able to reinstall everything on their own (or would just delete the app...). Just having a button to remove all items in one go (because most people didn't use that feature or could re-enable the syncs) and a pause button that will be paused by default so that people can decide what to do without having to put their phone in airplane mode, would be essential in my opinion.

I'm sure this issue is a ticking bomb for a lot of people, for some reason I noticed it after fdroid installed 3.30.2 on my phone, yesterday, and it started trying to sync one hour after this. I don't know what delayed the issue.

Even if I feel it's okay for me now that I have reinstalled everything from scratch (apart from the two way sync feature), I would still want a stop resume button, because if something like this starts to happen again but in the other direction, I would like to stop it immediately, like we can on the desktop client.

**Comment by githubtefo** [comment]
Unveleivable, they closed the original discussion for comments.
In my case, the solution for this DoSlike bug came from other users commenting on that post.

**Comment by turb** [comment]
FWIW for me it stopped doing that with 3.30.3 from /e/ OS store (using F-Droid).

**Comment by zukunft** [comment]
> ... A bug can happen...

I still think, it is a good idea, to limit the impact of a bug with https://github.com/nextcloud/android/issues/13873

**Comment by the-voidl** [comment]
I just noticed that the app in version 3.30.3 again started syncing files I don't want to be downloaded on my phone.
Opening the Nextcloud menu, there is the root folder `/` selected for 2-way-sync. I can remove it from the list by clicking the new X, but when starting the app for the next time, it again appears in the list.

I know the root folder should be excluded from sync in the patched versions but is that behavior wanted? At least to me it seems odd. Since removing other files from the list is persisted.

**Comment by dd900** [comment]
I just updated to v3.30.4 and I've NEVER had sync enabled at anytime. Immediately after the app updated it started downloading every file from my nextcloud to my phone. I went into the settings and internal two way sync was enabled for every folder on my nextcloud. Luckily I caught it or it would have maxed out my phone storage. Never at anytime should a setting that's not or that's never been enabled get "magically" enabled after an update. Please fix this!

**Comment by brezelman** [comment]
I'm on version 3.30.3 since release day on f-droid. This morning it started syncing every folder of my nextcloud. I didn't have the problem before (with 3.30.0, 3.30.1 or 3.30.2).

This issue still not fixed?

I tried stopping all sync processes, but the app is not reacting anymore. Help!
And then, there are hundreds of folders in the intern 2-way sync settings menu. You say, I have to remove them all manually? This is a nightmare, even if the app was reacting again. Are you kidding me? Implement the  "Remove all 2-way-syncs" button at least, as suggested by @timkrief.

**Comment by vrubiolo** [comment]
Hi there,

I am one of the people affected by the original bug who uninstalled the 3.30.1 version because of the issue (doubling my monthly data bill as a result).
I have been watching the various threads about the issue before jumping and reinstalling (I am using F-droid) but the latest comments make me wary of doing so.
Could we have an official stance on where we stand on the issue? According to the OP, it seems fixed but comments from @brezelman , @dd900 @the-voidl and @turb hint at the problem still being there 😨 ...
Thanks !

**Comment by turb** [comment]
> Could we have an official stance on where we stand on the issue? According to the OP, it seems fixed but comments from @brezelman , @dd900 @the-voidl and @turb hint at the problem still being there 😨 ...

For the record I was able to delete everything on 2-way sync settings, so I (happily) cannot test new versions on this bug.

**Comment by Zocker1999NET** [comment]
Looking at the recently merged PRs #13884 & #13905 and the [release notes of 3.30.4](https://github.com/nextcloud/android/releases/tag/stable-3.30.4), the Nextcloud devs are actively working on this issue without commenting here. Of course this is suboptimal communication given the possible severity of this issue, I still want to shout out some ❤️ and 👍 (& make the others here aware of the current progress).

So, there are now buttons for globally controlling 2way sync and to remove all 2way entries with one click. And assuming that the fixes are now in place (I have not tested v3.30.4 myself yet), Nextcloud Android should now respect those settings correctly & should not try to download the files even multiple times.

To summarize, from this thread, I for now only see two complaints which were not yet addressed:
1. quoted from dd900 [here](https://github.com/nextcloud/android/issues/13872#issuecomment-2450574467):
  > Never at anytime should a setting that's not or that's never been enabled get "magically" enabled after an update.
2. Users which had updated to 3.30.1 at some point may still have the unwanted setting for syncing all files 2way.

I don’t know if the Nextcloud devs have a chance of detecting somehow afterwards if a user was affected by this bug or not. But IMO I would still like to see an update pushed which disables 2way sync by default if 2way sync was enabled for the whole directory tree by #13738. That should address both complains mostly. And to catch users which had that deliberately (left) enabled, after that update, the app can push a notification stating that:
> To mitigate a bug, 2way sync was disabled for now.
> Due to this bug, 2way sync was enabled for some users without them wanting to, your device seem to be affected as well.
> (If you are part of an organization, please consult your IT admin team.)
> If you want to use 2way sync, you can safely enable it again now.
> If you did not want to use 2way sync and your phone has no storage left, you can now safely remove the `nextcloud` directory from your device which was created by this app. Your data will be left as is on your cloud.
> We are sorry for these circumstances. You can read more about *here (link)*.

I continue to propose this because:
- I think it is still safe to assume now that there are more users which will be annoyed by discovering this issue on their one (esp. as GitHub still seems the only channel this was communicated through) than users using 2way sync deliberately.
- IMO even if there are more users wanting/needing 2way sync than I assume, disabling it for them *and informing them about that* is still worth it if it helps a small amount of people to still/again have usable phones.
- especially IT admins from big organizations will have a better time when they can go through each affected phone, one by one (which is still bad enough), without their users’ phones burning through all battery, cellular data & storage.

**Comment by szotsaki** [comment]
Just for the record: no, 30.0.4 will _not_ end all of the remaining issues. You can opt out of two way sync and with that the various bugs.

One problem still remains: tens of gigabytes data scattered around which is impossible to remove without uninstalling the application or removing the account. As a **workaround**, this worked. As I wrote earlier:

> Please, create a proper, **automated** solution for this problem ASAP. Otherwise you offload solving this chaos to every single technical user who chose and distributed your application.

**Comment by brezelman** [comment]
> I tried stopping all sync processes, but the app is not reacting anymore. Help!

As I did not have time to "play" with this bug some longer, I had to uninstall the app for a quick "fix", as suggested in the first issue post here. I lost my synced files, but syncing some files again was way easier for me than removing hundreds of folder from planned sync, especially while the app wasn't reacting.
I switched to the play store version, too, because f-droid version doesn't have notifications support.

I suggest to the Nextcloud team: communicate, that the problem can still occur for people, who updated to 3.30.1. I was aware of the problem, but I didn't know, that the updated didn't fix the original bug.

**Comment by flixmart** [comment]
Just installed 3.30.4 after having used all of the 3.30.x F-Droid versions, including the full 3.30.1 impact on mobile allowance while travelling Africa :-(

Since clearing anything on the 2way sync page then and deleting any unwantedly synced contend from .../Android/media/com.nextcloud.client/... anything stayed calm since 3.30.2, although most confidence in sync and data integrity is gone for now.

But since 3.30.2 checking any folder from its context menue for sync just syncs once, never makes that folder appear on the 2 way sync page, which was basically "dead" since 3.30.2 until 3.30.4 . Now the new controls are present, but still never any content. So that still seems broken, at least without un-/reinstall. Do I have to? Did I miss that information? Where (is any official guidelines to be found)?

I had the understanding, that what was synced once (i.e. what was present under .../Android/media/com.nextcloud.client/...) was kept in sync. Has that ever been true? Is it still? Even with the unfunctional 2-way-sync page as per above?

I really like Nextcloud and its mobile apps 🙏, but this poorly introduced and documented and even more poorly handled fiasko on non beta apps becomes quite annoying. Sorry.

**Comment by noantiq** [comment]
Hi, so I updated to 3.30.4 today (F-Droid) and while I didn't experience any Issues with the previous Releases (including 3.30.1), today I was suddenly spammed with sync notifications and when I opened the app, it immediately crashed while trying to sync. This repeated until I turned off WiFi, opened the app an checked the settings to see that now, two-way sync for all of my files was enabled without my doing.

**Comment by lead0r** [comment]
> Hi, so I updated to 3.30.4 today (F-Droid) and while I didn't experience any Issues with the previous Releases (including 3.30.1), today I was suddenly spammed with sync notifications and when I opened the app, it immediately crashed while trying to sync. This repeated until I turned off WiFi, opened the app an checked the settings to see that now, two-way sync for all of my files was enabled without my doing.

For me as well, only happened when updating to 3.30.4. I'm confused because two-way sync should be disabled by default in this version again if I understand correctly?

I deleted the App and don't really know what to do now. Install again and disable two-way sync and then manually setting everything (including synced folders) again?

**Comment by timkrief** [comment]
> I'm sure this issue is a ticking bomb for a lot of people

When you update, two way sync should be paused and a popup should explain the situation...

**Comment by flixmart** [comment]
After updating to 3.30.4 it was enabled for me and on 15" shedule, although having and keeping  an emtpy list.

**Comment by flixmart** [comment]
> we have provided guidance and several options to stop any unwanted synchronisation attempts.
Since manually unchecking the whole tree from the two-way-sync page (afair still on 3.30.1), unwanted sync has not restarted for me.

But neither do I seem to be able to re-initiate any. (see above)

Also, although been mentioned in this thread, deleting all the unwanted content from the mobile client (by file manager), did not delete it from NC.

> and update the database to exclude those folders from being synchronised again.
Ever? Could that be the reason?

Before 3.30.x having synced p. e. my keepass database to mobile once automatically synced it back to NC, when changed on mobile. This still seems to work. Reliably? Re-syncing to mobile happened on access from the mobile NC client (if NC was online available)..

What additional benefit is two-way-sync intended to supply? Ensure "automatic" offline mobile availability of the latest accessible NC state?

Thanks

**Comment by flixmart** [comment]
BTW: 
Just read your initial post once more and realized, the hamburger menue isn't there for me on the internal two way sync page at all (3.30.4, Graphene OS / Android 15, dark)
So, whats the difference between disabling two way sync using the toggle and disabling it for all folders from the hamburger menue? Just fully clearing the list for the latter? Not available, bacause my list is empty?

**Comment by ZetaTom** [comment]
Dear Nextcloud Community,

Several users have reported that they are still experiencing problems after upgrading to version 3.30.4. As we are currently struggling to reproduce this specific behaviour, any additional data would be very valuable in our investigation. If you have upgraded to version 3.30.4 and are still affected, please follow the instructions below and let us know if the problem persists.
1. Open the Nextcloud Android Client
2. Disable two-way synchronisation (*Settings* → *Internal two way sync*)
3. Force close the client
	- The process of force closing an app varies from Android version to Android version. However, the general process will be similar to the following:
	1. Close the Nextcloud Android Client
	2. Long press on the app icon and select *App info*
	3. Tap on *Force stop* and confirm when prompted
	- If these options are not available to you, you can close the Nextcloud Android Client by using the app switcher.
4. Re-enable two-way synchronisation
5. Check if any folders are scheduled - tap *Disable for all folders* if that is the case
6. Disable two-way synchronisation again
7. Wait for 30-45 minutes
	- We want to make sure that the sync job has multiple opportunities to run.
	- By default, this happens every 15 minutes.

Once you have completed these steps, please report back to us with your findings.

Thank you for your cooperation!

**Comment by stop5** [comment]
> 1. Open the Nextcloud Android Client
> 2. Disable two-way synchronisation (*Settings* → *Internal two way sync*)
> 3. Force close the client
> 	- The process of force closing an app varies from Android version to Android version. However, the general process will be similar to the following:
> 	1. Close the Nextcloud Android Client
> 	2. Long press on the app icon and select *App info*
> 	3. Tap on *Force stop* and confirm when prompted
> 	- If these options are not available to you, you can close the Nextcloud Android Client by using the app switcher.
> 4. Re-enable two-way synchronisation
> 5. Check if any folders are scheduled - tap *Disable for all folders* if that is the case
> 6. Disable two-way synchronisation again
> 7. Wait for 30-45 minutes
> Thank you for your cooperation!

i did exactly this, but it still tries to sync files from my instance.

**Comment by flixmart** [comment]
Did that too: no unwanted syncs, but neither can trigger any to appear on the list. No hamburger menue either.

**Comment by mase76** [comment]
I have the opposite with 3.30.4. New added files to a synced folder are not uploaded.

**Comment by tuxayo** [comment]
> Once the client has attempted to synchronise a folder, the database records are indistinguishable from legitimate records. As a result, the client will continue to schedule any affected folders for synchronisation. However, we have provided guidance and several options to stop any unwanted synchronisation attempts.

Shouldn't it be better to be safe against the cases of unwanted sync enablement at the expense of the legitimate cases of willful use of sync?
Rather than preserving the cases of willful use of sync at the expense of keeping the cases of unwanted sync enablement? (Assuming I understood this as the current approach)

So the alternative would mean having an update that **disables too much sync setups to ensure not having unwanted syncs**. And it could notify users if two-way syncs have been disabled and they could choose to reenable those they confirm as legitimate.

It seems something like that would minimize the overall consequences of that case of having a state that is impossible to disambiguate from the bug and a legit two-way sync setup.

**Comment by vrubiolo** [comment]
Hello there, just a quick note to mention that I installed 3.30.4 from F-Droid and have not experienced any issue so far with sync. Two-way sync was enabled from the start after reinstall but no folders were listed. I disabled the feature using the new toggle.

Note that I had uninstalled 3.30.1 while waiting for a fix so I am probably in the 'ideal' scenario (app uninstalled).

As a sidenote, as I had to reconfigure my accounts after reinstalling the app, this messed up my NextCloud Notes Android App functionality (whose sync was timing out since I had uninstalled the main Nextcloud app). 
After Nextcloud 3.30.4 was reinstalled, I started experiencing new `TokenMismatchException` errors (cf [here](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#tokenmismatchexception)) and had to clear the Notes app storage. I thus lost the phone-only modifications I had pending for a few notes, which I manually exported and imported back once the Notes app started to work again. Just an FYI as the Notes app makes use of the accounts in the main Nextcloud app.

Thanks for the fix and the improved control, I will keep an eye on the issue on my end. I hope the issue sorts itself out for others and that there is a way to remove all the unwanted sync files.

**Comment by tobiasKaminsky** [comment]
> Did that too: no unwanted syncs, but neither can trigger any to appear on the list. No hamburger menue either.

Hamburger menu is hidden when sync is disabled.



> I have the opposite with 3.30.4. New added files to a synced folder are not uploaded.

Can you create a new issue for this?

**Comment by spaceChRiS** [comment]
I created a duplicate of this in #13977 because I was only affected by version 3.30.4, and not the minor releases before. Therefore, I kindly ask if somebody could change the title adding “(also happens in 3.30.2, 3.30.3 and 3.30.4)” such that no more duplicates are generated? Thanks!

**Comment by spaceChRiS** [comment]
As none of the above mentioned procedures in https://github.com/nextcloud/android/issues/13872#issuecomment-2461952811 did work so far, I wonder if I waited long enough such that the queue that has been filled before removing all folders from sync and disabling sync were emptied? Basically, the entire 100 GB of my wife's nextcloud account were added to the list, does that mean it will only stop after downloading them at least once? Or is the queue only a subset and is filled even after taking before-mentioned counter measures?

Btw, unfortunately I can report that at least in my case, disallowing mobile data background use does not stop nextcloud from synching even with wifi off.

**Comment by joe-average-user** [comment]
The whole thing is obviously broken by design. The "disable 2-way" option is not done correctly. If I do not want the client to download files at all there is simply no way implemented to perform this. The option, once 2-way was enabled (by default, another bug) there is no way back as the client seems to create a database which files to copy in which direction. And you cannot clear this database without being immediately recreated (by data in RAM?). Even if you completely remove cache and data from the app, the thing simply restarts the whole process again.
This is an unbelievably bad implementation of people never having heard of flow diagrams obviously.
You cannot even enter the Settings menu before you logged into your cloud. So turning off 2-way before it has cloud access (to get rid of the wrong default setting) is impossible too.

**Comment by tobiasKaminsky** [comment]
I think there are some things mixed up:
- 2 way sync for folders
- sync offline/downloaded files

The later runs in background since multiple years without any complaint nor bad notice.
The first one is new and it obeys the "disable 2 way sync option":
https://github.com/nextcloud/android/blob/c97082b17289c3d412822084948a4eb12e064f03/app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt#L42

Disabling it and removing cache and data should fix it, as then no  data shall be synced for above two cases.

**Comment by spaceChRiS** [comment]
> Disabling it and removing cache and data should fix it

OK, I did only empty cache because I thought that removing data would require a new account registration anyway. Is this not the case?

Anyway, I cannot test this anymore as my wife had to take her phone out of the house, and with 60 GB still not synced (likely on the queue) but only 50 GB of the annual data plan left, the only option was to reinstall.

**Comment by joe-average-user** [comment]
Disabling the option does obviously not help. And citing one line in the code doesn't say anything about other code that does restart the whole syncing again. This is what I meant by broken by design. The option does something, but only if the status of the app is in a certain state. Which it is mostly not if a sync is already running. The app does not even stop if you try to force-close it as requested by "the solution".
The only way I found to stop the problem is to uninstall the app and remove all cache and data. Then do a new install, switch off 2-way, and then re-configure all syncs again. Remember to ignore already existing files in the sync options, else all folders will be re-transmitted to the server, or you get asked thousands of replace-questions.
Everything else does not work!

**Comment by brotkastn** [comment]
Hello everyone,
i am currently on the "Nextcloud Dev Android App", from the F-Droid store. Today the nextcloud client downloaded 27,99GB while on LTE, which blew right through my whole data plan. All that while i did not enable 2 way sync.

If there is anything i can provide that helps to debug this problem, i am happy to help.

**Comment by joe-average-user** [comment]
Nobody enabled the 2-way sync. They made "enabled" the default. That is part of the problem, but not all of it.
Simply they failed the update path. You only have the chance to remove the app and re-install it.

**Comment by tobiasKaminsky** [comment]
@brotkastn from which version to which version was the update?

**Comment by mstenta** [comment]
I experienced this too - and as was stated before turning off the 2-way sync doesn't stop a sync that is already in progress. Force closing and restarting the app does not stop the sync either. As soon as I reopen it the syncing continues.

The only way I could find to stop it was to go into each folder, select all the files (by first long holding on one, then clicking the 3 dots in the top right and clicking "Select all"), then click the 3 dots in the top right again and click "Cancel sync". This needs to be done in each folder, which is tedious, but it's the only fix that worked. There doesn't appear to be a way to "Cancel sync" at the folder level (it would be nice to be able to click the top-level folder to cancel all below it).

After that, in order to remove the files that were downloaded, I went back to each folder that had synced (before I was able to cancel sync on them), clicked the 3 dots to the right of the folder name, clicked "Delete", and then (IMPORTANTLY) clicked "Local only".

One weird thing I noticed is that it did not try to download everything. I have my Nextcloud app configured to "Auto upload" certain directories (eg: "Camera"), and to "Store in subfolders based on date" on the server. What I noticed is that only the 2024 directory (and all month subdirectories) were added to the queue to be downloaded. But 2023, 2022, etc were not. Also, *only* my "photos" directory was added to the queue... not "videos", "download", etc. So I'm not sure what the logic was that chose which folders to automatically two-way sync, but I thought that was odd... 🤔

**Comment by mstenta** [comment]
Update: It did NOT work in fact!

Files are starting to sync again even though I went through and canceled them! I'm watching them (in one folder) get re-added to the queue automatically. And I can't find any way to stop it.

**Comment by joe-average-user** [comment]
> Update: It did NOT work in fact!
> 
> Files are starting to sync again even though I went through and canceled them! I'm watching them (in one folder) get re-added to the queue automatically. And I can't find any way to stop it.

Well, simply believe me. Whatever you read about "solutions", the only thing that does work is removing the app and re-installing, then disable 2.-way, and _then_ add your syncs again.
The ''2-way"' sync options is not the real cause of the problem. They seem to have broken the database-handling, which means they broke the update-path. Re-installing from scratch does not show the problem. Since the version is out now for some time there is probably no way back.
This is not the only place where nextcloud (and accompanying tools) has problems with the database handling. It is obvious there is no QA.

**Comment by rugk** [comment]
I use v3.30.4 and I've just encountered this issue (AFAIK) for the **first time**. So it seems not really fixed at all.
STR: IIRC, I just used KeePassDX to synchronize my (kbdx) file/DB, which I first downloaded (or so, when unlocking) and then pressed "Syncronize" in KeePassDX, which AFAIK uses the Android file provider to download the file, merge it, and upload it again

**Comment by rugk** [comment]
> includes button to stop all scheduled two-way sync operations and remove all folders from two-way sync

Where is that?

I've now disabled two-way sync via the button, but it continues to download files…

**Comment by joe-average-user** [comment]
You missed the point. your 2-way-sync implementation broke the sync as a whole. In fact every folder seems to get resynced continously, no matter what direction. I would say you misinterpret the sync-database in some point(field).
This does not happen on a fresh install, only in update path.

**Comment by tobiasKaminsky** [comment]
@joe-average-user can you explain in more detail what is broken?
With latest 3.30.5 we tried to fix the sync:
- all existing background jobs have been cancelled
- we now only use one background job to sync, which can be enabled/disabled and has a time interval in settings

So after upgrade, it should be enough to once/finally check if all your desired sync folders are in the settings list.

**Comment by joe-average-user** [comment]
Well, for understanding the problems, read the thread. 
Most - if not all - of us cannot check your latest update regarding the issue, as anyone I know needed an adhoc fix for the problem which only worked by removing the app, re-installing and re-adding the synced folders. Then the problem was gone. So I and probably others cannot tell you if 3.30.5 fixes it as we were not able to await this fix (the bug burned down all your mobile data volume as it disrepected the sync-during-wlan option completely).
Iow, all people constantly updating (by fdroid like me) were burnt...

**Comment by flixmart** [comment]
As per above I was badly having the problems on two devices when updating to 3.30.1 (FDroid). Both where  manually "repaired" initially and are online again afair since 3.30.3.

Both devices have only been updated through all versions since (no re-install), one to 3.30.4, the other to 3.30.5 since yesterday. Both have never again fallen back to unwanted syncs. 

In the meantime, even the two way sync seems to work as intended. 

@tobiasKaminsky 
The extended update notice and HowTos (OP of this thread) are helpfull ;-)

Do I understand correctly, that two way sync atm is hardcoded to WLan only, despite having sync-conditions options?

**Comment by AHeinlein** [comment]
I just wanted to give this a try, as I am still on 3.29.2 and have blocked updates on F-Droid since, waiting for this to be resolved. But F-Droid refuses to perform the update, it says the new version has been signed with a different key and that I need to uninstall and reinstall. Basically that means I am forced to do the "fix" the hard way... :-(

**Comment by alperozturk96** [comment]
@flixmart Yes. TwoWaySyncWorker will only work via Wi-Fi for now.

**Comment by tobiasKaminsky** [comment]
> I just wanted to give this a try, as I am still on 3.29.2 and have blocked updates on F-Droid since, waiting for this to be resolved. But F-Droid refuses to perform the update, it says the new version has been signed with a different key and that I need to uninstall and reinstall. Basically that means I am forced to do the "fix" the hard way... :-(

That is strange.
FDroid is responsible for building and signing it and so far I never saw a problem there (I am also using it).
Can you check on app details from which source it is installed?

**Comment by spaceChRiS** [comment]
> [@flixmart](https://github.com/flixmart) Yes. TwoWaySyncWorker is only working via Wi-Fi for now.

Are you referring to 3.30.5 explicitly or also to earlier revisions? Because with 3.30.4, it used 15 GB of my wife's mobile plan before I deinstalled it after all other countermeasures from this thread had failed.

**Comment by mase76** [comment]
When I put files into a synced folder via filemanager, they are not synced. NC does not know that files.

**Comment by alperozturk96** [comment]
> > [@flixmart](https://github.com/flixmart) Yes. TwoWaySyncWorker is only working via Wi-Fi for now.
> 
> Are you referring to 3.30.5 explicitly or also to earlier revisions? Because with 3.30.4, it used 15 GB of my wife's mobile plan before I deinstalled it after all other countermeasures from this thread had failed.

Since version [3.30.2](https://github.com/nextcloud/android/releases/tag/stable-3.30.2), it is only using Wi-Fi.

**Comment by spaceChRiS** [comment]
> Was Auto-Upload enabled with mobile data for some folders?

[...]

> However, if only mobile data is active, the Two-Way Sync Worker does not download anything.

Auto upload was active for the photo folder, but only allowed for wifi (and this worked for years now), plus she did not add 15 GB+ of new photos that day. And, I was able to reproduce with 3.30.4 that if I switch off wifi, the unstoppable syncing process kept running. It even re-spawned several times after deleting the app cache and other tries to stop it.

Unfortunately, I had to deinstall and reinstall the app to prevent more damage to my wife's yearly mobile plan¹, therefore I can no longer test this behavior.

¹It would anyway never have succeeded, even if I had kept the phone connected via wifi for several days: The entire nc folder was added to the sync list, way more than 100 GB of data (I wrote 100 GB before, but this was outdated information :wink:), which is more than the free space on the device anyway.

**Comment by alperozturk96** [comment]
> > Was Auto-Upload enabled with mobile data for some folders?
> 
> [...]
> 
> > However, if only mobile data is active, the Two-Way Sync Worker does not download anything.
> 
> Auto upload was active for the photo folder, but only allowed for wifi (and this worked for years now), plus she did not add 15 GB+ of new photos that day. And, I was able to reproduce with 3.30.4 that if I switch off wifi, the unstoppable syncing process kept running. It even re-spawned several times after deleting the app cache and other tries to stop it.
> 
> Unfortunately, I had to deinstall and reinstall the app to prevent more damage to my wife's yearly mobile plan¹, therefore I can no longer test this behavior.
> 
> ¹It would anyway never have succeeded, even if I had kept the phone connected via wifi for several days: The entire nc folder was added to the sync list, way more than 100 GB of data (I wrote 100 GB before, but this was outdated information 😉), which is more than the free space on the device anyway.

Thanks for the information. We were aware of the continuous syncing process and addressed it by stopping the scheduled worker at the beginning of the app launch in v3.30.5. We expect this issue to be resolved in v3.30.5.

As for the mobile data usage still occurring in v3.30.4, we will look into it.

**Comment by bobemoe** [comment]
I was hit by this too right at the beginning and uninstalled after my monthly allowance was consumed! I am watching this thread closely and waiting for it to become stable enough for me to reinstall.

One thing I have read is that sync is now limited to WiFi. I have no WiFi and do all my sync on Ethernet. I think this needs to be amended to allow sync on Ethernet or it wont even work for me when I do reinstall? https://github.com/nextcloud/android/pull/13847#pullrequestreview-2425080855

**Comment by tobiasKaminsky** [comment]
> One thing I have read is that sync is now limited to WiFi. I have no WiFi and do all my sync on Ethernet (or mobile). I think this needs to be amended to allow sync on Ethernet too (and a toggle for mobile) or it wont even work for me when I do reinstall? [#13847 (review)](https://github.com/nextcloud/android/pull/13847#pullrequestreview-2425080855)

Adding an option to also run it on mobile data, is possible.

**Comment by joe-average-user** [comment]
Ok,, with 3.30.5 you managed to break the auto-upload alltogether.
Now the status is that some folders get auto-uploaded and others dont. Namely the first folder (Camera) does not get uploaded any more. I tried everything besides de-installing and re-installing. It does not help. Camera folder does not get uploaded any more, whereas pictures from Conversations (XMPP messenger) do, but screenshots dont. Auto-upload is now really completely broken. Please everybody, check_all_ your auto-upload folders if they really still work.

**Comment by RikkiBC** [comment]
> Ok,, with 3.30.5 you managed to break the auto-upload alltogether. Now the status is that some folders get auto-uploaded and others dont. Namely the first folder (Camera) does not get uploaded any more. I tried everything besides de-installing and re-installing. It does not help. Camera folder does not get uploaded any more, whereas pictures from Conversations (XMPP messenger) do, but screenshots dont. Auto-upload is now really completely broken. Please everybody, check_all_ your auto-upload folders if they really still work.

I'm not seeing this myself either, but it sounds like a new issue that would be best in its own bug report if you're experiencing it.

**Comment by tobiasKaminsky** [comment]
We did not changed any thing auto-uploaded related.
Is Camera or any other in 2-way sync list? 
Else I think it is indeed unrelated.

**Comment by joe-average-user** [comment]
2-way sync is turned off with the corresponding button. I have problems in understanding where a 2-way sync list is to be found? My understanding so far was that turning on 2-way sync affects the "standard" sync list - as it did this when the option was broken...
I really do not want to turn it on ever again, so I fail to see if there are any further config options coming up after that.

**Comment by tobiasKaminsky** [comment]
@joe-average-user which version do you use?
You should be able to see it in settings -> internal two-way sync.

There you can also disable it.
The list will be shown beneath the "interval".


![Image](https://github.com/user-attachments/assets/0a6f08ea-5047-40fc-9dca-0ff183f0f9c3)

**Comment by rugk** [comment]
Gosh have reenabled two-way-sync in the past and selected three directories and now or seems to have downloaded my whole nextcloud. See https://github.com/nextcloud/android/issues/14738
