### ISSUE TITLE
Intermittent upload failures from Android client (Nexus 5x)

### ISSUE THREAD

**Issue by radegand** [nextcloud/android#288]
Hi,
### Actual behaviour

-During an upload of selected files, some files fail to upload without an obvious reason. The behaviour is intermittent. The weird thing is, it doesn't matter if I start the upload in any of the following ways:
1) open 'photos' app and use 'share' functionality to upload it to my nextcloud server
2) open the nextcloud app and use its upload functionality to select files from the 'photos' app
3) via the web interface using Chrome Web Browser on my Nexus - it also fails (for instance, after one picture has been uploaded, it just stop uploading the next ones, without any error)

for steps 1) and 2), if I try to re-upload the failing photos, they will fail again.

This problem seems to be unique to my Nexus 5X device. I have a Samsung tablet and a Samsung mobile phone and they upload all files successfully all the time.
My issue looks somehow similar to #287 , however my logs seem to be a bit different.
### Expected behaviour
- All selected files should be upload successfully to the selected forlder.
### Steps to reproduce
1. Select number of photos to upload, either via the 'photos' app or the nextcloud app itself
2. Upload to the selected folder
3. watch it fail intermittently. 
### Environment data

Android version:
7.0
Device model: 
Nexus 5X
Stock or customized system:
stock
Nextcloud app version:
1.3.1
Nextcloud server version:
10.0
The server is running on my home network only, OS Ubuntu 16.04 on Odroid (ARM)
#### Web server error log

```
192.168.2.21 - user [24/Sep/2016:08:22:25 +0200] "GET /ocs/v1.php/cloud/users/user?format=json HTTP/1.1" 200 2149 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:25 +0200] "GET /index.php/avatar/user/336 HTTP/1.1" 200 1340 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:25 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1102 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:25 +0200] "PROPFIND /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 207 2037 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:26 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150754.jpg HTTP/1.1" 404 1115 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.
1"
192.168.2.21 - user [24/Sep/2016:08:22:26 +0200] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2FPhotos%2FPraca%2F2016%2F&reshares=true&subfiles=true HTTP/1.1" 200 2086 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:26 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1100 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:27 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150801.jpg HTTP/1.1" 404 1125 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:28 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:28 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150811.jpg HTTP/1.1" 404 1119 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:29 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1108 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:30 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150825.jpg HTTP/1.1" 404 1111 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:31 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1110 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:31 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150837.jpg HTTP/1.1" 404 1115 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:32 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1114 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:33 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_150857.jpg HTTP/1.1" 404 1115 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:34 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1104 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:35 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_151509.jpg HTTP/1.1" 404 1117 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:35 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1108 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:36 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_151516.jpg HTTP/1.1" 404 1129 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:37 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:37 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_151521.jpg HTTP/1.1" 404 1115 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:38 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:39 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_151524.jpg HTTP/1.1" 404 1117 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:39 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/ HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.2.21 - user [24/Sep/2016:08:22:40 +0200] "HEAD /remote.php/webdav/Photos/Praca/2016/IMG_20160920_152712.jpg HTTP/1.1" 404 1115 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
```
#### Nextcloud log (data/nextcloud.log)

nothing there :(

I've posted logcat output from my Nexus here:
http://pastebin.com/k9LsafcJ

In this case, out of the 11 files I've tried to upload only 7 (I think) ended up successfully uploaded to the server.

**Comment by kvoit** [comment]
> This problem seems to be unique to my Nexus 5X device. I have a Samsung tablet and a Samsung mobile phone and they upload all files successfully all the time.

Author of #287 here: Have you uploaded a lot from your Nexus 5X? Have you also not uploaded lot from the other devices?
As I added in my report, this behavior only occurs (and then apparently stays) after successfully uploading 50-100 images (estimated, without having counted) for me. With both my OP3 and my wife's Z3, I could upload a whole bunch of images before it persistently stopped working.

**Comment by radegand** [comment]
Hi,
No, I haven't uploaded many files from my Nexus, just a bunch of them. The annoying thing is it's very intermittent and I can't find a reason why some pictures are uploaded while others aren't

My nextcloud.log is owned by www-data, still nothing gets logged there when pictures fail to upload.

Also, it's not just my nexus - I've tried uploading 199 pics from my Samsung tables and 184 uploaded successfuly. If I try to reupload the failing one, they will fail again.

Oh, maybe worth mentioning - I have a collection of my pictures in nextcloud so it's approx 40k files in different folders...

**Comment by AndyScherzinger** [comment]
@radegand I can't find a source for the issue in the logs either, but I might just don't see it... @tobiasKaminsky di you have any idea on why this is happening?

**Comment by radegand** [comment]
Hi,
I'm happy to do more debugging if necessary, this is really annoying and fairly consistent for me in its inconsistency. :)
Can I enable more debugging on the Android client and/or the server?

Thanks in advance.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this is the log for one of the images (server and folder name anonymized):
```
09-24 08:22:31.097 26065 27543 D OwnCloudClient #45: REQUEST HEAD /remote.php/webdav/Photos/folder-name/2016/
09-24 08:22:31.334  6496  6496 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
09-24 08:22:31.754 26065 27543 D ExistenceCheckRemoteOperation: Existence check for http://server-address/remote.php/webdav/Photos/folder-name/2016/ targeting for  existence finished with HTTP status 200
09-24 08:22:31.859 26065 27543 D UploadFileOperation: Checking name collision in server
09-24 08:22:31.860 26065 27543 D OwnCloudClient #45: REQUEST HEAD /remote.php/webdav/Photos/folder-name/2016/IMG_20160920_150857.jpg
09-24 08:22:32.780 26065 27543 D ExistenceCheckRemoteOperation: Existence check for http://server-address/remote.php/webdav/Photos/folder-name/2016/IMG_20160920_150857.jpg targeting for  existence finished with HTTP status 404(FAIL)
09-24 08:22:32.787 26065 27543 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg status:UPLOAD_IN_PROGRESS result:-1)
09-24 08:22:32.787 26065 27543 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg with status=UPLOAD_IN_PROGRESS
09-24 08:22:32.804 26065 27543 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg
09-24 08:22:32.804 26065 27543 D UploadsStorageManager: notifyObserversNow
09-24 08:22:32.811 26065 27543 E UploadFileOperation: Upload of /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg to /Photos/folder-name/2016/IMG_20160920_150857.jpg: Operation finished with HTTP status code -1 (fail)
09-24 08:22:32.811 26065 27543 D UploadsStorageManager: updateDataseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@e5bb148 upload: com.owncloud.android.operations.UploadFileOperation@2be9be1
09-24 08:22:32.815 26065 27543 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg status:UPLOAD_IN_PROGRESS result:-1)
09-24 08:22:32.815 26065 27543 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg with status=UPLOAD_FAILED
09-24 08:22:32.825 26065 27543 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20160920_150857.jpg
09-24 08:22:32.825 26065 27543 D UploadsStorageManager: notifyObserversNow
09-24 08:22:32.826 26065 27543 D FileUploader: NotifyUploadResult with resultCode: UNKNOWN_ERROR
```

To resolve this matter we should increase logging in this area for one of the upcoming beta client releases to find the root cause of this behavior.

**Comment by AndyScherzinger** [comment]
I modified the logging in the beta app a little https://github.com/nextcloud/android/pull/169/commits/59355d38d5de3babcff3369ebe7d15be7dfef719 that should give us the translated result code. It seems this issue is to be found deep down in the client library :(

**Comment by radegand** [comment]
Looks like we're making some progress on this then :)
How can I get the beta client with your patch? Will there be a separate apk provided somehow?
Thanks!

**Comment by AndyScherzinger** [comment]
@radegand yes :) The apk can be downloaded installed from f-droid: https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta - the logging will be part of the next beta release. Beware that you do not have to uninstall the "standard" Nextcloud client since the beta can run next to it :grin: 

@tobiasKaminsky can you ping @radegand as soon as we do a new beta release? :)

**Comment by radegand** [comment]
Hi,

So I've tried with the latest beta (20-10-2016), what's the best way to provide you with logs? They're too big to past on pastebin and I'm not sure what parts are relevant.

Thanks

**Comment by iskradelta** [comment]
What is easiest for you, maybe a peer2peer file share website/tool such as http://ge.tt/ or https://www.file.io/ or https://instant.io/ or https://www.sharefest.me/ https://reep.io/ or old-school tool mega.cz I believe, and share the file there, either in full or as a zip to save space, or send an email to me or another developer here?

**Comment by kvoit** [comment]
I presume he might have access to a Nextcloud instance for a shared link. SCNR.

**Comment by AndyScherzinger** [comment]
Hi @radegand if you can reproduce the error I'd say, clear the log first, then reproduce the error then check the log, it should then be much smaller. Other than that we are most likely looking for so called stack traces thus logging blocks that start with "Exception" in it should do the trick. :)

**Comment by radegand** [comment]
Hi,
I have share the logcat logs here: http://ge.tt/5RkGXqf2
The app itself didn't seem to create any log files. The list under "settings" -> "logs" is empty. Is there a way to turn it on specifically?

Thanks,
Radek

**Comment by AndyScherzinger** [comment]
Hi @radegand 
unfortunately I couldn't find any detailed information in the log, just ```status:UPLOAD_IN_PROGRESS and result:UNKNOWN``` there is no way to explicitly turn on the log, it should be working out of the box.

@nickvergessen @MorrisJobke anything you can read from the server logs above?

**Comment by MorrisJobke** [comment]
> I have share the logcat logs here: http://ge.tt/5RkGXqf2

This is not a server log :(

**Comment by AndyScherzinger** [comment]
@MorrisJobke I meant above above --> https://github.com/nextcloud/android/issues/288#issue-179020304

**Comment by iskradelta** [comment]
@radegand If the app doesnt show the logs (bug...), check for it with a file manager, it should be on internal storage, where your Download and DCIM folders are, called nextcloudbeta inside it is log with currentLog.txt. On android 6/cyanogenmod 13, its in /sdcard/nextcloudbeta/log/

**Comment by radegand** [comment]
Hi,
Apologies for the late response. I've just updated my server to 11.0. The problem remains. You can find my log file from the beta Android client here: https://file.io/xPa6ji  
No error got logged on the server side in nextcloud.log file. Please let me know if you need more logs/data.
Thanks.

**Comment by Sevlin** [comment]
Hi,

TL;DR (workaround)

Disable `fastcgi_intercept_errors` in nginx configuration.
`fastcgi_intercept_errors on;` to `fastcgi_intercept_errors off;`

---

I've faced same issue multiple times (on ownCloud and Nextcloud). In my case source of the problem was caused by nginx configuration (default virtual host config obtained from official documentation).

Android client uses HEAD method to check whether file exists or not. If `fastcgi_intercept_errors` is enabled in location that handles php, then client recieves 200 even though php returned 404.

**Comment by radegand** [comment]
@Sevlin thanks for the suggestion, but I run Apache not nginx :-( and I don't see any fastcgi apache alternatives being enabled.

@iskradelta , @AndyScherzinger do you have any other suggestions guys? Any other logs I can get you?

This issue is really annoying and is preventing me from making a proper use of nextcloud as a storage :-(

Thanks in advance.

**Comment by OlivierS1** [comment]
I have seen this issue or the like under Nextcloud beta 20170107.
I can't say what is the cause of it, but it would seem it is causing connection issues. It could be my Owncloud Server 9.1.1 running NGINX, but I will need to investigate.
All I know thus far, is that my phone could upload files, and upload fails there is a possibility that connecting to the server from my deskstop over LAN has proven unsuccselful at times, because of time-outs. Not sure it is related to this issue or something else.
I need to keep it an eye though

**Comment by OlivierS1** [comment]
Remote loging to the server after some dead time, I get the following events from the log:

> Exception: {"Exception":"TypeError","Message":"Argument 8 passed to OC\\Core\\Controller\\AvatarController::__construct() must implement interface OCP\\Files\\Folder, null given, called in \/usr\/local\/www\/owncloud\/core\/Application.php on line 95","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/core\/Application.php(95): OC\\Core\\Controller\\AvatarController->__construct('core', Object(OC\\AppFramework\\Http\\Request), Object(OC\\AvatarManager), Object(OC\\Cache\\File), Object(OC\\L10N\\L10N), Object(OC\\User\\Manager), Object(OC\\User\\Session), NULL, Object(OC\\Log))\n#1 \/usr\/local\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(113): OC\\Core\\Application->OC\\Core\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#2 \/usr\/local\/www\/owncloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(102): Pimple\\Container->offsetGet('AvatarControlle...')\n#3 \/usr\/local\/www\/owncloud\/lib\/private\/AppFramework\/App.php(93): OC\\AppFramework\\Utility\\SimpleContainer->query('AvatarControlle...')\n#4 \/usr\/local\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#5 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#6 \/usr\/local\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#7 \/usr\/local\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/avatar\/Nextclo...')\n#8 \/usr\/local\/www\/owncloud\/index.php(39): OC::handleRequest()\n#9 {main}","File":"\/usr\/local\/www\/owncloud\/core\/Controller\/AvatarController.php","Line":81}

> 
And a few of the following, which might trigger my firewall anti brute force hammering and cause to block my IP address:

> Login failed: '----------' (Remote IP: 'XX.XX.XX.XX')

**Comment by OlivierS1** [comment]
Interrestingly enough, the account that is triggering the "Login failed" originate from my beta tester account on my server. However, the few hundred file transfer is done from another account in Nextcloud app.
So far I have 4 accounts setup.
I suspect that maybe the reason on the "Login Failed"  is triggered by the app trying to connect with one account login and for some reason, either use the wrong password or maybe the request is being interleaved causing password and account names to be sent in wrong order.

**Comment by OlivierS1** [comment]
Getting rid of the account causing problem, I am now able to upload files, but it is not really a clean and error free process.
Here is the error log from server when doing large upload:

> Exception: {"Message":"HTTP\/1.1 404 File with name 20160328 (2).gpx could not be located","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(79): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('20160328 (2).gp...', 0)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(251): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), false)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpHead(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:HEAD', Array)\n#8 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/usr\/local\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#10 \/usr\/local\/www\/owncloud\/remote.php(164): require_once('\/usr\/local\/www\/...')\n#11 {main}","File":"\/usr\/local\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":170,"User":"XXXXXX"} 

>

**Comment by kvoit** [comment]
I am also experiencing this problem again on my Oneplus 3. Nextcloud 11, App beta updated from F-Droid yesterday.

This is the the smallest possible log I can create for one failed reupload (Delete log - restart failed upload - go back to log - send)

```
2017/01/26 07:24:42
LogHistoryActivity : onPause() ending

2017/01/26 07:24:42
Preferences : onStart() starting

2017/01/26 07:24:42
Preferences : onResume() starting

2017/01/26 07:24:42
LogHistoryActivity : onStop() ending

2017/01/26 07:24:42
LogHistoryActivity : onDestroy() ending

2017/01/26 07:24:46
Preferences : onPause() ending

2017/01/26 07:24:46
FileDisplayActivity : onDestroy() start

2017/01/26 07:24:46
FileDisplayActivity : onDestroy() ending

2017/01/26 07:24:46
FileDisplayActivity : onDestroy() end

2017/01/26 07:24:46
FileDisplayActivity : onCreate() start

2017/01/26 07:24:46
FileDisplayActivity : onCreate(Bundle) starting

2017/01/26 07:24:46
FileDisplayActivity : onCreate() end

2017/01/26 07:24:46
FileDisplayActivity : onStart() start

2017/01/26 07:24:46
FileDisplayActivity : onStart() starting

2017/01/26 07:24:46
FileDisplayActivity : Initializing Fragments in onAccountChanged..

2017/01/26 07:24:46
FileDisplayActivity : Access to unexisting list of files fragment!!

2017/01/26 07:24:46
FileDisplayActivity : Still have a chance to lose the initializacion of list fragment >(

2017/01/26 07:24:46
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:46
FileDisplayActivity : onStart() end

2017/01/26 07:24:46
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:46
OwnCloudClient #1768 : Creating OwnCloudClient

2017/01/26 07:24:46
OwnCloudClient #1769 : Creating OwnCloudClient

2017/01/26 07:24:46
SimpleFactoryManager :     new client {kay@cloud.example.org, 23833138}

2017/01/26 07:24:46
SimpleFactoryManager :     new client {kay@cloud.example.org, 224322435}

2017/01/26 07:24:46
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:46
OwnCloudClient #1770 : Creating OwnCloudClient

2017/01/26 07:24:46
FileDisplayActivity : Access to unexisting list of files fragment!!

2017/01/26 07:24:46
OwnCloudClient #1769 : REQUEST GET /ocs/v1.php/cloud/users/kay

2017/01/26 07:24:46
SimpleFactoryManager :     new client {kay@cloud.example.org, 84605184}

2017/01/26 07:24:46
FileDisplayActivity : Access to unexisting list of files fragment!!

2017/01/26 07:24:46
FileDisplayActivity : OCFileListFragment is null

2017/01/26 07:24:47
FileDisplayActivity : onResume() start

2017/01/26 07:24:47
FileDisplayActivity : onResume() starting

2017/01/26 07:24:47
OwnCloudClient #1770 : REQUEST GET /ocs/v1.php/cloud/users/kay

2017/01/26 07:24:47
Avatar : URI: https://cloud.example.org/index.php/avatar/kay/384

2017/01/26 07:24:47
OCFileListFragment : onAttach

2017/01/26 07:24:47
OwnCloudClient #1768 : REQUEST GET /index.php/avatar/kay/384

2017/01/26 07:24:47
OCFileListFragment : onCreateView() start

2017/01/26 07:24:47
ExtendedListFragment : onCreateView

2017/01/26 07:24:47
OCFileListFragment : onCreateView() end

2017/01/26 07:24:47
OCFileListFragment : onActivityCreated() start

2017/01/26 07:24:47
FileDisplayActivity : onResume() end

2017/01/26 07:24:47
FileActivity : Operations service connected

2017/01/26 07:24:47
FileDisplayActivity : Download service connected

2017/01/26 07:24:47
FileDisplayActivity : Upload service connected

2017/01/26 07:24:47
FileObserverService : Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.android.beta/com.owncloud.android.services.observer.FileObserverService }

2017/01/26 07:24:47
FileObserverService : Loading all kept-in-sync files from database to start watching them

2017/01/26 07:24:47
Preferences : onStop() ending

2017/01/26 07:24:47
Preferences : onDestroy() ending

2017/01/26 07:24:47
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:47
OwnCloudClient #1771 : Creating OwnCloudClient

2017/01/26 07:24:47
SimpleFactoryManager :     new client {kay@cloud.example.org, 8804401}

2017/01/26 07:24:47
OwnCloudClient #1771 : REQUEST GET /status.php

2017/01/26 07:24:47
UpdateOCVersionOperation : Got new OC version 11.0.0.10

2017/01/26 07:24:47
UpdateOCVersionOperation : Check for update of ownCloud server version at https://cloud.example.org/remote.php/webdav: Operation finished with HTTP status code -1 (success)

2017/01/26 07:24:47
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:47
OwnCloudClient #1772 : Creating OwnCloudClient

2017/01/26 07:24:47
SimpleFactoryManager :     new client {kay@cloud.example.org, 251177750}

2017/01/26 07:24:47
OwnCloudClient #1772 : REQUEST GET /ocs/v1.php/cloud/capabilities

2017/01/26 07:24:47
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:47
OwnCloudClient #1773 : Creating OwnCloudClient

2017/01/26 07:24:47
SimpleFactoryManager :     new client {kay@cloud.example.org, 218479767}

2017/01/26 07:24:47
Avatar : URI: https://cloud.example.org/index.php/avatar/kay/384

2017/01/26 07:24:47
OwnCloudClient #1773 : REQUEST GET /index.php/avatar/kay/384

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"version":{"major":11,"minor":0,"micro":0,"string":"11.0.0","edition":""},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false},"expire_date":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false},"group_sharing":true,"federation":{"outgoing":true,"incoming":true}},"notifications":{"ocs-endpoints":["list","get","delete","icons","rich-strings"]},"theming":{"name":"Nextcloud","url":"https:\/\/nextcloud.com","slogan":"a safe home for all your data","color":"#0082c9","logo":"https:\/\/cloud.example.org\/core\/img\/logo.svg","background":"https:\/\/cloud.example.org\/core\/img\/background.jpg"},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true}}}}}

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : *** Added version

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : *** Added core

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : *** Added files_sharing

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : *** Added files

2017/01/26 07:24:48
GetRemoteCapabilitiesOperation : *** Get Capabilities completed 

2017/01/26 07:24:48
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:48
OwnCloudClient #1774 : Creating OwnCloudClient

2017/01/26 07:24:48
SimpleFactoryManager :     new client {kay@cloud.example.org, 246513284}

2017/01/26 07:24:48
OwnCloudClient #1774 : REQUEST GET /ocs/v1.php/cloud/user

2017/01/26 07:24:49
GetRemoteUserInfoOperation : Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"id":"kay","display-name":"Kay-Michael Voit","email":"kay@example.org"}}}

2017/01/26 07:24:49
RefreshFolderOperation : Got display name: com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation$UserInfo@d09fef0

2017/01/26 07:24:49
RefreshFolderOperation : Checking changes in kay@cloud.example.org/

2017/01/26 07:24:49
OwnCloudClient #1771 : REQUEST PROPFIND /remote.php/webdav/

2017/01/26 07:24:49
RefreshFolderOperation : Checked kay@cloud.example.org/ : not changed

2017/01/26 07:24:49
RefreshFolderOperation : Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED

2017/01/26 07:24:49
OwnCloudClient #1771 : REQUEST GET /ocs/v1.php/apps/files_sharing/api/v1/shares

2017/01/26 07:24:49
FileDisplayActivity : Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED

2017/01/26 07:24:49
FileDisplayActivity : Setting progress visibility to true

2017/01/26 07:24:50
GetRemoteSharesForFileOperation : Got 0 shares

2017/01/26 07:24:50
FileDataStorageManager : Sending 17 operations to FileContentProvider

2017/01/26 07:24:50
FileContentProvider : applying batch in provider com.owncloud.android.providers.FileContentProvider@26e22c9 (temporary: false)

2017/01/26 07:24:50
FileContentProvider : applied batch in provider com.owncloud.android.providers.FileContentProvider@26e22c9

2017/01/26 07:24:50
RefreshFolderOperation : Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED

2017/01/26 07:24:50
FileDisplayActivity : Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED

2017/01/26 07:24:50
FileDisplayActivity : Setting progress visibility to false

2017/01/26 07:24:50
FileDisplayActivity : onPause() start

2017/01/26 07:24:51
FileDisplayActivity : onPause() ending

2017/01/26 07:24:51
FileDisplayActivity : onPause() end

2017/01/26 07:24:51
UploadListActivity : onCreate(Bundle) starting

2017/01/26 07:24:51
UploadListActivity : onStart() starting

2017/01/26 07:24:51
ExpandableListFragment : onCreateView

2017/01/26 07:24:51
UploadListFragment : onActivityCreated() start

2017/01/26 07:24:51
UploadListFragment : onStart() start

2017/01/26 07:24:51
ExpandableUploadListAdapter : ExpandableUploadListAdapter

2017/01/26 07:24:51
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:51
ExpandableUploadListAdapter : registerDataSetObserver

2017/01/26 07:24:51
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:51
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:51
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:51
OwnCloudClient #1775 : Creating OwnCloudClient

2017/01/26 07:24:51
OwnCloudClient #1776 : Creating OwnCloudClient

2017/01/26 07:24:51
SimpleFactoryManager :     new client {kay@cloud.example.org, 104812974}

2017/01/26 07:24:51
OwnCloudClient #1777 : Creating OwnCloudClient

2017/01/26 07:24:51
SimpleFactoryManager :     new client {kay@cloud.example.org, 237738537}

2017/01/26 07:24:51
UploadListActivity : onResume() start

2017/01/26 07:24:51
SimpleFactoryManager :     new client {kay@cloud.example.org, 242023247}

2017/01/26 07:24:51
OwnCloudClient #1776 : REQUEST GET /ocs/v1.php/cloud/users/kay

2017/01/26 07:24:51
UploadListActivity : onResume() starting

2017/01/26 07:24:51
UploadListActivity : onResume() end

2017/01/26 07:24:51
Avatar : URI: https://cloud.example.org/index.php/avatar/kay/384

2017/01/26 07:24:51
OwnCloudClient #1777 : REQUEST GET /ocs/v1.php/cloud/users/kay

2017/01/26 07:24:51
OwnCloudClient #1775 : REQUEST GET /index.php/avatar/kay/384

2017/01/26 07:24:51
FileActivity : Operations service connected

2017/01/26 07:24:51
UploadListActivity : UploadListActivity not connected to Upload service. component: ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.files.services.FileDownloader} service: com.owncloud.android.files.services.FileDownloader$FileDownloaderBinder@4cc8947

2017/01/26 07:24:51
UploadListActivity : UploadListActivity connected to Upload service. component: ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.files.services.FileUploader} service: com.owncloud.android.files.services.FileUploader$FileUploaderBinder@43330f3

2017/01/26 07:24:51
FileDisplayActivity : onSaveInstanceState() start

2017/01/26 07:24:51
FileDisplayActivity : onSaveInstanceState(Bundle) starting

2017/01/26 07:24:51
ExtendedListFragment : onSaveInstanceState()

2017/01/26 07:24:51
FileDisplayActivity : onSaveInstanceState() end

2017/01/26 07:24:51
FileDisplayActivity : onStop() start

2017/01/26 07:24:51
FileDisplayActivity : onStop() ending

2017/01/26 07:24:51
FileDisplayActivity : onStop() end

2017/01/26 07:24:52
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:52
OwnCloudClient #1778 : Creating OwnCloudClient

2017/01/26 07:24:52
SimpleFactoryManager :     new client {kay@cloud.example.org, 13068497}

2017/01/26 07:24:52
Avatar : URI: https://cloud.example.org/index.php/avatar/kay/384

2017/01/26 07:24:52
OwnCloudClient #1778 : REQUEST GET /index.php/avatar/kay/384

2017/01/26 07:24:52
ExpandableUploadListAdapter : refreshView

2017/01/26 07:24:52
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:52
FileUploader : Starting command with id 366

2017/01/26 07:24:52
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status=UPLOAD_IN_PROGRESS

2017/01/26 07:24:52
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg

2017/01/26 07:24:52
UploadsStorageManager : notifyObserversNow

2017/01/26 07:24:52
ExpandableUploadListAdapter : refreshView

2017/01/26 07:24:52
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:52
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg status:UPLOAD_IN_PROGRESS result:-1)

2017/01/26 07:24:52
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status=UPLOAD_IN_PROGRESS

2017/01/26 07:24:52
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg

2017/01/26 07:24:52
UploadsStorageManager : notifyObserversNow

2017/01/26 07:24:52
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:52
OwnCloudClient #1779 : Creating OwnCloudClient

2017/01/26 07:24:52
SimpleFactoryManager :     new client {kay@cloud.example.org, 59293965}

2017/01/26 07:24:52
OwnCloudClient #1779 : REQUEST HEAD /remote.php/webdav/SofortUpload/

2017/01/26 07:24:52
ExpandableUploadListAdapter : refreshView

2017/01/26 07:24:52
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:53
ExistenceCheckRemoteOperation : Existence check for https://cloud.example.org/remote.php/webdav/SofortUpload/ targeting for  existence finished with HTTP status 200

2017/01/26 07:24:53
UploadFileOperation : Checking name collision in server

2017/01/26 07:24:53
OwnCloudClient #1779 : REQUEST HEAD /remote.php/webdav/SofortUpload/IMG_20170115_154530.jpg

2017/01/26 07:24:54
ExistenceCheckRemoteOperation : Existence check for https://cloud.example.org/remote.php/webdav/SofortUpload/IMG_20170115_154530.jpg targeting for  existence finished with HTTP status 404(FAIL)

2017/01/26 07:24:54
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg status:UPLOAD_IN_PROGRESS result:-1)

2017/01/26 07:24:54
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status=UPLOAD_IN_PROGRESS

2017/01/26 07:24:54
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg

2017/01/26 07:24:54
UploadsStorageManager : notifyObserversNow

2017/01/26 07:24:54
ExpandableUploadListAdapter : refreshView

2017/01/26 07:24:54
UploadFileOperation : Upload of /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg to /SofortUpload/IMG_20170115_154530.jpgResultCode(UNKNOWN_ERROR): Operation finished with HTTP status code -1 (fail)

2017/01/26 07:24:54
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:54
UploadsStorageManager : updateDataseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@91a58c2 upload: com.owncloud.android.operations.UploadFileOperation@f4f16d3

2017/01/26 07:24:54
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg status:UPLOAD_IN_PROGRESS result:-1)

2017/01/26 07:24:54
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg with status=UPLOAD_FAILED

2017/01/26 07:24:54
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg

2017/01/26 07:24:54
UploadsStorageManager : notifyObserversNow

2017/01/26 07:24:54
FileUploader : NotifyUploadResult with resultCode: UNKNOWN_ERROR

2017/01/26 07:24:54
FileUploader : Stopping command after id 366

2017/01/26 07:24:54
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:54
OwnCloudClient #1780 : Creating OwnCloudClient

2017/01/26 07:24:54
SimpleFactoryManager :     new client {kay@cloud.example.org, 228679484}

2017/01/26 07:24:54
ExpandableUploadListAdapter : refreshView

2017/01/26 07:24:54
ExpandableUploadListAdapter : loadUploadItemsFromDb

2017/01/26 07:24:58
UploadListActivity : onPause() start

2017/01/26 07:24:58
UploadListActivity : onPause() ending

2017/01/26 07:24:58
UploadListActivity : onPause() end

2017/01/26 07:24:58
Preferences : onCreate(Bundle) starting

2017/01/26 07:24:58
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2017/01/26 07:24:58
OwnCloudClient #1781 : Creating OwnCloudClient

2017/01/26 07:24:58
SimpleFactoryManager :     new client {kay@cloud.example.org, 9558600}

2017/01/26 07:24:58
Preferences : onStart() starting

2017/01/26 07:24:58
Preferences : onResume() starting

2017/01/26 07:24:58
UploadListActivity : onSaveInstanceState(Bundle) starting

2017/01/26 07:24:58
ExtendedListFragment : onSaveInstanceState()

2017/01/26 07:24:58
UploadListActivity : onStop() ending

2017/01/26 07:25:00
Preferences : onPause() ending

2017/01/26 07:25:00
LogHistoryActivity : onCreate(Bundle) starting

2017/01/26 07:25:00
LogHistoryActivity : onStart() starting

2017/01/26 07:25:00
LogHistoryActivity : onResume() starting

2017/01/26 07:25:00
Preferences : onSaveInstanceState(Bundle) starting

2017/01/26 07:25:00
Preferences : onStop() ending

2017/01/26 07:25:01
LogHistoryActivity : onPause() ending

2017/01/26 07:25:04
LogHistoryActivity : onSaveInstanceState(Bundle) starting

2017/01/26 07:25:04
LogHistoryActivity : onStop() ending

```

**Comment by AndyScherzinger** [comment]
Any one having th etime to further analyze this? @mario @tobiasKaminsky 
The probably important log statement is:
```
UploadFileOperation : Upload of /storage/emulated/0/DCIM/Camera/IMG_20170115_154530.jpg to /SofortUpload/IMG_20170115_154530.jpgResultCode(UNKNOWN_ERROR): Operation finished with HTTP status code -1 (fail)
```

**Comment by mario** [comment]
@tobiasKaminsky probably knows a lot more than I do about the upload code at the moment.

**Comment by OlivierS1** [comment]
Could it be related to Quota on the server side?
When I set Quota on one of my server account, it caused some accounts to not being able to upload any files anymore.
I couldn't get any logs from the phone runinng 1.4.0 I think, and it would return unknown error.
If you have access to the logs in the server, it will tell you if quota is the issue.
Increasing the quota resolved the issue.
This could be a shot in the dark but who knows.

**Comment by tobiasKaminsky** [comment]
Can I maybe have a test account where I can upload a bunch of images, in order to see (maybe) more while debugging the app?

**Comment by kvoit** [comment]
Of course. I haven't seen a possibility for private messages in GitHUB. Are you the IAT guy and can I send the credentials to the institute email?

**Comment by tobiasKaminsky** [comment]
Just send it to "android @ nextcloud . com" with a link to this issue.
(But yes I am, I just want to keep both separate)

**Comment by tobiasKaminsky** [comment]
@kvoit is this bug still present?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
