### ISSUE TITLE
[3.3.0 RC1] Unlock with fingerprint not available

### ISSUE THREAD

**Issue by ffuentes** [nextcloud/android#2968]
### Actual behaviour
- After upgrading to v3.3.0 RC1, unlocking with fingerprint is not available. Previous versions allow this.

### Expected behaviour
- Able to unlock with fingerprint.
 

### Environment data
Android version: 8.0.0.OPR1

Device model: Xiaomi Mix 2

Stock or customized system:

Nextcloud app version: v3.3.0 RC1

Nextcloud server version: 13.0.4

**Comment by AndyScherzinger** [comment]
@ffuentes thanks for the report. What setting is active in the apps settings screen for the app lock? (Can you post a screenshot of it maybe?) Thanks :)

**Comment by ffuentes** [comment]
Hi @AndyScherzinger , can't take screenshot it says is not allowed.

The settings was on and working before updating, after it. It posible to select credential, but it just ask for the code not the fingerprint.

Here are some photos...
![img_20180905_110308923](https://user-images.githubusercontent.com/17456/45098738-ff38ea00-b0fb-11e8-88fd-3fb223624f3e.jpg)

Not posible to take android screenshot.
![img_20180905_110743](https://user-images.githubusercontent.com/17456/45098801-27c0e400-b0fc-11e8-8dc9-3782e7526c63.jpg)

**Comment by AndyScherzinger** [comment]
Ah, yeah, my mistake, screenshots are blocked on screens with possibly sensitive information.

@tobiasKaminsky do you have any idea what is happening here, @ardevd maybe or @rhari991 ?

**Comment by AndyScherzinger** [comment]
@ffuentes do you have a screenshot of the pin code screen (with keyboard hidden)?

**Comment by AndyScherzinger** [comment]
I checked it on my phone and it works fine, of course is asks for the credentials (PIN) _or_ the fingerprint within the one screen

**Comment by ffuentes** [comment]
@AndyScherzinger it only ask for PIN when is selected Access code. If I check credential it just open the app without fingerprint or PIN code.

**Comment by meyerf99** [comment]
@AndyScherzinger I have the same issue with fingerprint Authentication. Nextcloud want authenticate with Threema App :(

If you need some settings, ask me.

**Comment by tobiasKaminsky** [comment]
This is the old pin screen. This should only be shown with "pin" enabled and not "device credentials".

@meyerf99 what do you mean with "authenticate with threema app"?

**Comment by meyerf99** [comment]
When i want to open Nextcloud Android App it ask me for fingerprint.
Thats normal because i set unlock with fingerprint. But with the newest Beta release v.3.3.0 RC1 it open Threema fingerprint unlock and not Nextcloud fingerprint unlock.

**Comment by tobiasKaminsky** [comment]
With 3.3.0 we use the unlock screen from android. 
Maybe also Threema is using the same so it leads to the impression that it is the one from Threema…
But @meyerf99 is it working for you to unlock the app?

**Comment by meyerf99** [comment]
@tobiasKaminsky Oke, no it is not possible.
I think thats a big issue...

**Comment by ffuentes** [comment]
@tobiasKaminsky this is the android unlock screen?

![img_20180907_102742366](https://user-images.githubusercontent.com/17456/45221863-2bce3c80-b289-11e8-9895-a42ea8cb5fe9.jpg)

It appears only when changing from device credentials to access code, but after that it only prompts for the PIN code with the other screen.

**Comment by meyerf99** [comment]
@tobiasKaminsky & @AndyScherzinger

V.3.3.0 RC2 didn't solved my problem.

**Comment by ffuentes** [comment]
@AndyScherzinger @tobiasKaminsky me neither, RC2 still doesn't ask for fingerprint on my device, it just open the app.

**Comment by AndyScherzinger** [comment]
We know, RC2 just fixed two crashes in other areas of the app.
As soon as we come up with a solution and implementation it would be linked against this issue. 
Still I have no clue how to solve this. @tobiasKaminsky maybe we need to offer the old fingerprint solution too for devices that don't support the Android device credentials Api properly :/

**Comment by MeiRos** [comment]
To me it says something like "use biometric or draw your pattern". Upper part of the screen is just white. I think there should be camera screen to help iris check. Now it's hard to find correct angle and position to check my iris. Any idea why it's like that?

The checking accepts fingerprint even it doesn't mention about it.

Lower part is for pattern. Dots where you draw. And it's working also. 

My device is Samsung S8.

**Comment by fdjean** [comment]
Same here

**Actual behaviour**
After upgrading to v3.3.0 RC2, unlocking with fingerprint is not available. Previous versions allow this.
**Expected behaviour**
Able to unlock with fingerprint.
**Environment data**
Android version: 7.1.2
Device model: Xiaomi Redmine 4 Prime
Stock or customized system:
Nextcloud app version: v3.3.0 RC2
Nextcloud server version: 14.0.0 RC2

**Comment by warthog9** [comment]
So I'll tag onto this, after setting / un-setting credentials a bunch to get it reset (it seemed to require credentials with 'none' set for a bit), I got it back to asking for my login pin (the new menu), however just assuming my fingerprint would work (since my device is setup for it) did in fact unlock.  That being said there's no indication of that being the case, and there's just the pin/pattern/etc unlock being shown so it's not obvious that fingerprint should work.  I'm on Nextcloud app: v3.3.0 RC2

**Comment by AndyScherzinger** [comment]
@warthog9 the unlock screen you are seeing is from the operating system as-in Android not from the app, the app is just requesting the authentication via the operating system. I also don't see a fingerprint symbol on the screen before I close the virtual keyboard that comes up, so this in fact a quite weird UX decision by Google... :S

**Comment by tobiasKaminsky** [comment]
For me (emulator & OTP3 with LineageOS) it looks this way:
![image](https://user-images.githubusercontent.com/5836855/45359596-4841e000-b5cd-11e8-892a-ba7fd34e4019.png) ![image](https://user-images.githubusercontent.com/5836855/45359616-568ffc00-b5cd-11e8-8d10-b54af8ebf361.png)

**Comment by meyerf99** [comment]
@tobiasKaminsky For me it looks like yours and it looks like Threema fingerprint authentication.

**Comment by AndyScherzinger** [comment]
@meyerf99 I guess threema, like nextcloud is using the Android OS authentication mechanism for the device credentials ;)

**Comment by joekerna** [comment]
Is this related to #3026 and #2879 ?

**Comment by AndyScherzinger** [comment]
I think so, yes

**Comment by Pablohn26** [comment]
Same problem here with Xiaomi Mi Mix 2S and Nextcloud dev 20181013

**Comment by meyerf99** [comment]
@AndyScherzinger & @tobiasKaminsky 
It's horrible to work with this Nextcloud App version. It's not possible to log-in with fingerprint.
ETA for fix?

**Comment by tobiasKaminsky** [comment]
We had a bug with fingerprint (un)lock mechansim. It affected only a few devices, e.g. Xiaomi, Motorola, …
As none of our test deices was affected, hunting this bug down took a while.

If any of you could download and install this apk (https://cloud.nextcloud.com/s/pCwRFo7rFF3MMjM) and test if it is now working better, I would appreciate it.
(the APK file is signed with the key for Google Play Store and is 3.3.2 Alpha 1, so this proves that it is an official version and can be easily upgraded. The up-to-come 3.3.2 version then can also just update this version).

**Comment by joekerna** [comment]
Does the fingerprint work, even though you're not asked for it? That's what's happening on my side (Also Huawei P9)

**Comment by tobiasKaminsky** [comment]
Enabling it in settings:
![2018-10-31-131212](https://user-images.githubusercontent.com/5836855/47787297-c9387080-dd0e-11e8-8c09-b08bc4f2e4dc.png)


After timeout (10s) I started NC app:
(this screen can be a bit different, depending on vendor/device)
![screenshot_20181031_131256](https://user-images.githubusercontent.com/5836855/47787298-c9387080-dd0e-11e8-83ea-a7f91a54e076.png)

**Comment by tobiasKaminsky** [comment]
@p3x-robot what is happening for you if you use the fingerprint? Nothing at all? Do you see an error?

**Comment by tobiasKaminsky** [comment]
@p3x-robot can you compare with @joekerna as he also has a P9? And for him it is working…
Maybe he has a newer android version?

**Comment by joekerna** [comment]
> 
> 
> @joekerna for you Nextclud the fingerprint works???

Yes... No fingerprint symbol and I don't understand why I'm asked for a PIN also but fingerprint works just fine.

**Comment by joekerna** [comment]
> 
> 
> @tobiasKaminsky looks in the Android 7 implementation the device credentials is missing the icon, though it works... that is what is happening.

:) that's what I was saying earlier. Not beautiful but working

**Comment by tobiasKaminsky** [comment]
Glad that it is working now also for you, @p3x-robot.
@joekerna yeah, unfortunately there is nothing we can do here…

**Comment by joekerna** [comment]
Does Android provide options that change the way it looks? As mentioned it looks different (but the same) on apps like Lastpass, Enpass, comdirect trade, PayPal, Deutsche Bank,...

**Comment by tobiasKaminsky** [comment]
@joekerna can you give me some screenshots how it looks for you on NC an don other apps?

**Comment by joekerna** [comment]
Nextcloud
![img_20181101_095539](https://user-images.githubusercontent.com/23077594/47873681-223cfd00-de12-11e8-927e-f61ea70c1536.jpg)
Other apps
![img_20181101_095555](https://user-images.githubusercontent.com/23077594/47873683-223cfd00-de12-11e8-865e-7995a62fae30.jpg)
![img_20181101_095715](https://user-images.githubusercontent.com/23077594/47873686-22d59380-de12-11e8-961f-969d2d0a059f.jpg)

**Comment by paulsommer** [comment]
I can confirm the bug. It exists in 3.3.1 as well as in the dev Version.
I just re-installed ver 3.2.1 from my Backup, and this version works with fingerprint.
System is a OnePlus 3 with rooted current LineagaOS.

For now I'll stick with 3.2.1 and switch off auto update.

**Comment by AndyScherzinger** [comment]
@paulsommer since you run a OP3 with Lineage (like @tobiasKaminsky) 3.3.x should just work fine. As described in this issue the client uses Android's native authentication which unfortunately doesn't really show that you can use the fingerprint while using the fingerprint sensor will unlock the app.

Some devices had an issue with how the authentication actually worked so @tobiasKaminsky created a fix which is part of 3.3.2 (RC1 has been released to the Play store already)

**Comment by tobiasKaminsky** [comment]
@paulsommer please try 3.3.2 which was released right now.

@joekerna I assume that the other apps have implemented the fingerprint dialog on their own.
If there is an open source app that has a different screen, I can have a look.

**Comment by ffuentes** [comment]
Ain't fixed in **v3.3.2** RC1 for Xiaomi mi mix 2.

It does ask for the phone pin code but, doesn't work with the fingerprint.

**Comment by ffuentes** [comment]
@AndyScherzinger , @tobiasKaminsky seems that this depends in how vendor firmware is implemented, right?

Can you point me an app to double check this?

Thanks.

**Comment by paulsommer** [comment]
> @paulsommer please try 3.3.2 which was released right now.

Yeah! Works for me now. Big thanks :-)

**Comment by meyerf99** [comment]
@tobiasKaminsky @AndyScherzinger
Problem solves in android app v.3.3.2
Thanks :)

**Comment by MikeWallaceDev** [comment]
Still not working in the version 3.4.1
I'm on a Xiaomi Redmi Note 4. MiUI 10.1 (which is Android 7.0)
App does not show fingerprint icon. Trying fingerprint anyway doesn't work. 
Default Android fingerprint dialog works with other apps (banking, Zoho Vault,...)

**Comment by Pablohn26** [comment]
Same problem here with Xiaomi Mi Mix 2S and Nextcloud dev 20181222

**Comment by tobiasKaminsky** [comment]
This seems to be then a very specific problem for Xiamoi.
@skjnldsv what Xiaomi device do you have?
