### ISSUE TITLE
Unable to disable Device credentials

### ISSUE THREAD

**Issue by ajostergaard** [nextcloud/android#3166]
### Actual behaviour

Once the Lock setting has been set to Device credentials changing it to None has no effect, i.e. the app still requires Device credentials.

### Expected behaviour

When Lock is set to None no credentials should be required to open it.

May seem like a trivial complaint but unless I can disable this I cannot take screenshots of the app. 

### Steps to reproduce
1. Set Lock to Device Credentials
2. Kill and re-open the app
3. Set Lock to None
4. Kill and re-open the app

### Environment data
Android version: 9 (Pie) Oct patch level

Device model: Essential PH-1

Stock or customized system: Stock

Nextcloud app version: 3.3.0 (F-Droid)

Nextcloud server version: 14.0.3

### Logs

If somebody could clarify where to get applicable logs am happy to provide.

**Comment by ajostergaard** [comment]
Yes, and a sliding notice at the bottom of the screen saying 'Credentials disabled'. Funnily enough when I enable them again afterwards there's no screen to confirm credentials and only a sliding notice saying 'Device credentials enabled'. Almost as if it knows they are already enabled to no need to confirm that I know them.

**Comment by codingHahn** [comment]
I can reproduce this on LineageOS 15.1 Oreo

**Comment by cbrace** [comment]
I'm seeing this behaviour on my Moto 4G phone running Android v7. I have tried all the lock settings to disable the nextcloud swipe-screen lock.

My major issue with the client lock is that it doesn't cache credentials for any period of time, which makes it extremely cumbersome to use when sharing a series of files through the client. A useful enhancement (in addition to fixing this bug) would IMO to offer a optional credential caching, ie, 15 mins, 1 hour, etc

**Comment by tobiasKaminsky** [comment]
We had a bug with fingerprint (un)lock mechansim. It affected only a few devices, e.g. Xiaomi, Motorola, …
As none of our test deices was affected, hunting this bug down took a while.

If any of you could download and install this apk (https://cloud.nextcloud.com/s/pCwRFo7rFF3MMjM) and test if it is now working better, I would appreciate it.
(the APK file is signed with the key for Google Play Store and is 3.3.2 Alpha 1, so this proves that it is an official version and can be easily upgraded. The up-to-come 3.3.2 version then can also just update this version).

**Comment by ajostergaard** [comment]
Very keen to try it, downloaded the apk but when I open it F-Droid offers to install it and then just says App not installed. When I select Open With it just open F-Droid... Any ideas?

**Comment by tobiasKaminsky** [comment]
@ajostergaard how did you installed the current app? via Gplay or via fdroid?

**Comment by ajostergaard** [comment]
F-Droid

**Comment by tobiasKaminsky** [comment]
@ajostergaard then please try this version: https://cloud.nextcloud.com/s/BDybFQ4CfQf9Jet

You can install it in parallel to your regular app, it will be called "Nextcloud dev". Only downside is that you have to setup an account to test it.
Afterwards you can simply remove it.

**Comment by ajostergaard** [comment]
Thanks! Can I login with my regular self-hosted account or do I need to setup a new account?

**Comment by ajostergaard** [comment]
Seems to be working! 👍 :)))

**Comment by tobiasKaminsky** [comment]
Glad to hear and thanks for testing :+1:

**Comment by cbrace** [comment]
I can confirm that the APK version fixed this issue on my Moto G4. Many thanks!

**Comment by LeoDJ** [comment]
I still have this exact issue on version 3.7.1 and a Oneplus 3T with Android 9

**Comment by tobiasKaminsky** [comment]
@LeoDJ which device credential do you use?
Can you try to enter your device pin when trying to disable?

**Comment by LeoDJ** [comment]
I tried it with both fingerprint and pin code using the same procedure from "steps to reproduce" above.
Both times the Nextcloud app showed a toast "Credentials disabled"

Can you clarify what you mean by "which device credentials"? I can say that it appears to me that the stock settings-overlay is used (I can see this in the application switcher) prompting me to "Re-enter your PIN", where I can either enter my PIN or use my fingerprint.

**Comment by LeoDJ** [comment]
I just tried to set it from "Device credentials" to "Passcode", but now I have to enter both Device credentials and the custom passcode. After setting it to "None", I'm back to only Device credentials.

I didn't have a look in the code, but it feels to me like it is somehow not correctly telling the Android system to stop protecting the app, but I'm just guessing

**Comment by tobiasKaminsky** [comment]
> I just tried to set it from "Device credentials" to "Passcode", but now I have to enter both Device credentials and the custom passcode. After setting it to "None", I'm back to only Device credentials.

You should not be able to set both…

To not mess with your current app, can you try our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

Can you there test it again?

I fear that somehow the setting can not be removed, but I have no idea why and how to prevent this…

**Comment by LeoDJ** [comment]
Hm, using the dev version, disablinig the device credentials worked as it should.

So it's probably a stuck setting in my Android system somehow, because I enabled Device Credentials for Nextcloud a long time ago and just now wanted to disable them again. I guess some update has broken the link that allows NC to disable it, or something like that, I don't really know.

I fear this will only be solved by an app re-install, although I'm not fond of it, I might try it later this week and report back.

**Comment by kopierschnitte** [comment]
I've re-installed the app and still can't disable biometric login on my Samsung Note8. Strange.

**Comment by ajostergaard** [comment]
> I've re-installed the app and still can't disable biometric login on my Samsung Note8. Strange.

Have you tried leaving it uninstalled overnight before reinstalling? Have found this to help sometimes, seems Android cleans up overnight or something.

**Comment by kopierschnitte** [comment]
Great idea. Can't believe it really worked.
Thanks!
