### ISSUE TITLE
App crashes upon start.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#4129]
### Actual behaviour
- Tell us what happens. 
Since update to what seems to be NC 3.7.0.RC2, NC is crashing upon start. I have no way to connect to my servers using the app, and update from my phone obviously cannot be performed.
I wish there was a way to revert to a state prior to this update.
In a nutshell, I am in dead water.
I am thinking, that maybe I should pull out of the Beta testing program if no fall back options is made available.

### Expected behaviour
- Tell us what should happen.It should work. Nothing more simple than that.
 
### Steps to reproduce
1. Start NC.

### Environment data
Android version:
4.4.2
Device model: 
SGH-I747M
Stock or customized system:
Stock
Nextcloud app version:
3.7.0.RC2
Nextcloud server version:
16.0.1
15.0.8

### Logs
Not available
#### Web server error log
```
Insert your webserver log here
```Not relevat as crash does also occur without wifi connection.

#### Nextcloud log (data/nextcloud.log)
```Not relevat as crash does also occur without wifi connection.

Insert your Nextcloud log here
```
Report from my phone was sent earlier today.

**Comment by ezaquarii** [comment]
1. What happens if you reinstall the app from scratch?

2. Can you pls provide a stacktrace? Nextcloud staff is off for a long weekend (I guess judging from public holiday calendar), but I could maybe give it a look in the meantime.

**Comment by Claonilton** [comment]
**My Nextcloud version: 3.6.2**
In    my device Android 7.1.1 _when click in ENTER the app is closed._
In other device Android 8.1.0 Normal

**Comment by MeiRos** [comment]
Reinstalled my Nextcloud app RC. No help.
Crashing after drawing and after iris check. 

Downloaded/installed 3.6.2 from F-Droid. It's working. Now I can go back to beta in the Play Store when I want to.

Samsung Galaxy S8
Stock/latest updates
Android 9
Nextcloud server 15 (latest)

**Comment by Wikinaut** [comment]
Same here on some of my devices:

* HUAWEI Y6 2018 Android 8.0.0
* HUAWEI P8 LITE 2015 Android 6.0

**Comment by Wikinaut** [comment]
Same for NC 3.7.0 RC3 - crashes upon start.

**Comment by AndyScherzinger** [comment]
@Wikinaut since there haven't been any logcats yet, are you able to provide one (and the corresponding stack trace) of the crash?

**Comment by Wikinaut** [comment]
@AndyScherzinger Sorry, I cannot provide you with logs. It happens on the above mentioned devices.

**Comment by emresaracoglu** [comment]
![ezgif-2-24637e7fbb24](https://user-images.githubusercontent.com/297968/59542673-b413f900-8f0f-11e9-8c0b-99432e9fac13.gif)


HUAWEI P8 LITE 2015 Android 6.0

**Comment by ezaquarii** [comment]
> @Wikinaut since there haven't been any logcats yet, are you able to provide one (and the corresponding stack trace) of the crash?

@AndyScherzinger, can you get ACRA PR against  NC 3.7.0 RC3? That would allow users to actually generate a stack trace for us. No need to "release" - just QA build should do the trick.

**Comment by ezaquarii** [comment]
@emresaracoglu  are you able to use ADB to dump the stack trace?

**Comment by emresaracoglu** [comment]
@ezaquarii Unfortunately, this is currently impossible. I haven't installed Android Studio after the format.

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger, can you get ACRA PR against NC 3.7.0 RC3? That would allow users to actually generate a stack trace for us. No need to "release" - just QA build should do the trick.

@ezaquarii sure thing: #4154 should do the trick

**Comment by ezaquarii** [comment]
@AndyScherzinger , splendid!

@emresaracoglu can you try to reproduce this problem with a build  #4154 ?

There is a QR code with/and URL with a test APK - if you install it, it should launch an email composer with stacktrace when the app crashes. This way we can get to the bottom of the issue.

**Comment by ezaquarii** [comment]
@OlivierS1 @Wikinaut @MeiRos  can you as well try to reproduce this problem with a build #4154 ?

**Comment by emresaracoglu** [comment]
@ezaquarii I uploaded it and tested it.

The application started without a crash 👍

**Comment by ezaquarii** [comment]
@emresaracoglu That is... not good at all. It means that this issue is more elusive.

I'm affraid we'll need to grap a stacktrace with original build via ADB, or we'll be fooled by some "quantum effects".

@AndyScherzinger do you believe those 2 builds differ in some significant way? I can think about Google Play APIs only. This could potentially have some extra impact.

**Comment by emresaracoglu** [comment]
I restarted the phone and the application crashed.
I sent you an e-mail to log.

@ezaquarii

**Comment by ezaquarii** [comment]
@emresaracoglu thank you. Your crash is most useful as it confirmed similarity to #4150.

**Comment by ezaquarii** [comment]
@emresaracoglu @OlivierS1 @Claonilton @MeiRos @Wikinaut

We have a fix pending. I invite everybody to test it. QA build is available here: https://github.com/nextcloud/android/pull/4155#issuecomment-502457085

**Comment by emresaracoglu** [comment]
Great @ezaquarii but the application crashes when touched to open the video.

**Comment by ezaquarii** [comment]
@emresaracoglu Thanks, the 2nd issue is fixed in a separate PR. I think we can ship them as one fix, instead of 2 separate. I'll make a new PR.

**Comment by ezaquarii** [comment]
@emresaracoglu @OlivierS1 @Claonilton @MeiRos @Wikinaut

We have a fix pending. I invite everybody to test it. QA build is available here: https://github.com/nextcloud/android/pull/4156#issuecomment-502460078

**Comment by emresaracoglu** [comment]
The `9757.apk` file is running great! **Thank you** for your contribution to this project @ezaquarii 

[Video](https://datarals.com/s/ikkJw6KCC8kj76L)

**Comment by Wikinaut** [comment]
Sorry, boys and girls, my trust level in your Android App is limited, and the lowest level has been reached.

**Comment by OlivierS1** [comment]
> 
> 
> @emresaracoglu @OlivierS1 @Claonilton @MeiRos @Wikinaut
> 
> We have a fix pending. I invite everybody to test it. QA build is available here: [#4156 (comment)](https://github.com/nextcloud/android/pull/4156#issuecomment-502460078)

It seems on my system it is still crashing.
I have been away and unable to follow up on this issue but I might be able to focus a bit on this the following few days.
So far, this is a NO GO! for me.
With QA installed, I am not able to send feedbacks.

One thing that have been troubling for me since I had to perform an uninstall of my Android app, is that I am no longer able to enable "App passcode". For some reason, when ever I try to set it up, I am asked for the password, and confirmation. But upon entering both without obvious difference, the "app password" is never activated.
To me it is a safety featutre that lacks safety status, however, I have notice this behavior on a Pixel phone and thought little of it at the time as there is fingerprint recognition at play, but i think something isn't quite right in the curernt state of the app.
I have been using the Beta for quite some time, and I haven't had to do a fresh install in a fairly long time, and I suspect, as a result of being a beta tester, I haven't gone through the hassle of starting evaluatinig the app from a fresh install property, then we it is my understanding we might be facing some  issues that have been caused on fresh system long before. 
Upgrading from one release to the next, just proves what ever is currently installed doesn't break. It doesn't mean a fresh install will behave the same.
I think there is an Intrinsic flaw in how beta testing is being performed.

I will be working off my laptop, which doesn't have Android studio installed. In the essence of time and simplicity,, can you give me the breaking down steps that will allow me to extract the log stack you request. If I have a no brainer process, I will be able to come with the results quite quickly, I would think.

**Comment by OlivierS1** [comment]
@AndyScherzinger 
What email address should I use to send the logcat to?

**Comment by AndyScherzinger** [comment]
I guess since @ezaquarii is looking into this matter : hello (at) ezaquarii dot com

**Comment by OlivierS1** [comment]
@AndyScherzinger, Thanks, I have sent two logcats to @ezaquarii  one for the 3.7.0-RC2 or RC3 and NC-QA-9757.

**Comment by ezaquarii** [comment]
Youp, go ahead. I'll take a look.
