### ISSUE TITLE
Charging progress

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4401]
**1.** Loading progress appears all the time with photos displayed.

### Steps to reproduce
1. Choose "Photos" from the menu.

![obraz](https://user-images.githubusercontent.com/47037905/63588171-248d6500-c5a6-11e9-8148-dfad06770915.png)

**2.** The loading progress appears all the time.

### Steps to reproduce
1. Choose "Photos" from the menu.
2. Choose "Shared" or "Favorites" from the menu.

![obraz](https://user-images.githubusercontent.com/47037905/63588282-6cac8780-c5a6-11e9-8b27-a16f62e16849.png)

### Environment data
Android version: 6

Nextcloud app version: dev-20190823 and 3.8.0 RC2

Nextcloud server version: 16.0.4

**Comment by tobiasKaminsky** [comment]
We have issues for this already: #1682, but photos should be better with 3.8.0 RC2.
If not please comment on those existing issues.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it is happending when you navigate to favorite or shared (coming from photos) so it is not fixed with the photos improvement

**Comment by Valdnet** [comment]
I got this error today. It appeared when loading photos for a long time.

> ************ CAUSE OF ERROR ************
> 
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 	at java.lang.Thread.run(Thread.java:818)
> Caused by: java.lang.IllegalStateException: Fragment PhotoFragment{25794a9} not attached to a context.
> 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
> 	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:90)
> 	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:38)
> 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	... 4 more

### Environment data

Android version: 6
Nextcloud app version: dev-20190905
Nextcloud server version: 16.0.4

**Comment by tobiasKaminsky** [comment]
@Valdnet you can test this with APK in #4475, it can be installed parallel.

**Comment by Valdnet** [comment]
@tobiasKaminsky After testing the https://www.kaminsky.me/nc-dev/android-artifacts/10855.apk version, the problem is as follows:
- After selecting "Photos" photos are displayed, but loading progress remains (operation is unstable, sometimes, only loading progress appears).

![obraz](https://user-images.githubusercontent.com/47037905/64426367-a86b4500-d0ae-11e9-850f-7e565bc261c6.png)

- After selecting first, e.g. "favorites", favorite files are displayed with the information "no files" #4400. Then choosing "Photos",  only the loading progress with "+" is displayed.

![obraz](https://user-images.githubusercontent.com/47037905/64426847-f896d700-d0af-11e9-92bc-060a1d033f40.png)

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/4485 and will be in RC5.

**Comment by Valdnet** [comment]
> Fixed via #4485 and will be in RC5.

@tobiasKaminsky The RC5 version still has the same problem.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Valdnet** [comment]
@tobiasKaminsky Data sent.

**Comment by Valdnet** [comment]
@tobiasKaminsky In version 3.8.1 there is still a problem with loading and displaying photos.

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky since this issue is still present according to @Valdnet (I didn't have the time to reproduce)

**Comment by Valdnet** [comment]
Problem has been solved. Only double charging needs to be refined.
Issue: #6684.
