### ISSUE TITLE
Auto-Upload tries to upload several times although successful

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/android#644]
### Actual behaviour
- Creates 2 upload instances when autouploading 
- Succeeds uploading one of them
- Tries to upload the second instance of the screenshot that was uploaded and calls it `filename (2).jpg`
- Fails trying to upload the copy

### Expected behaviour
- Just upload the screenshot
 
### Steps to reproduce
1. Fresh setup
2. Activate autoupload and change upload folder to /pics/
3. Take a screenshot

### Environment data
Android version: 
OOS 4.0.2

Device model: 
Oneplus 3

Stock or customized system:
Stock, rooted

Nextcloud app version:
20170209

Nextcloud server version:
11.0.1

**Comment by mario** [comment]
Thanks for the report. New beta, once out, should fix this.

**Comment by tobiasKaminsky** [comment]
Latest beta is out: https://github.com/nextcloud/android/blob/beta/apks/latest.apk

**Comment by aronovgj** [comment]
Now it uploads both screenshots. The original and the copy.

**Comment by mario** [comment]
Can you please uninstall, install it again and see if duplicates still
appear?

**Comment by aronovgj** [comment]
I already reinstalled it and I am not able to reproduce it consistently

![screenshot_20170211-145555](https://cloud.githubusercontent.com/assets/10271770/22854261/95c2d7d2-f06a-11e6-85b5-74d32ce9c640.png)

**Comment by aronovgj** [comment]
On yet another reinstall I see this:

![screenshot_20170211-150304](https://cloud.githubusercontent.com/assets/10271770/22854298/9fe41c7a-f06b-11e6-9239-6caf00355f2d.png)


and then this:

![screenshot_20170211-150314 2](https://cloud.githubusercontent.com/assets/10271770/22854300/a873a0d6-f06b-11e6-97f1-f06e33788098.png)

**Comment by mario** [comment]
Strange, this was fixed. I will investigate - thanks

**Comment by aronovgj** [comment]
Also the settings menu crashes since the new beta

**Comment by mario** [comment]
Andy, Tobias,

Any idea what changed with settings?

**Comment by tobiasKaminsky** [comment]
> Also the settings menu crashes since the new beta

I updated all branches in the beta app and did a merge wrong :/
You can re-download https://github.com/nextcloud/android/blob/beta/apks/latest.apk as I updated it.

**Comment by aronovgj** [comment]
Yep settings now work again, double uploads still happen though.

**Comment by mario** [comment]
That sounds strange :( I will check on Monday

**Comment by mario** [comment]
Please try the latest beta build in a link given by @tobiasKaminsky .

**Comment by aronovgj** [comment]
Issue seems to be gone. Thanks!

**Comment by mario** [comment]
Thanks @aronovgj! :)
