### ISSUE TITLE
Conflict prompt on Auto Upload with "Overwrite remote version" checked

### ISSUE THREAD

**Issue by jeroenev** [nextcloud/android#6938]
### Steps to reproduce
1. Add a folder to auto upload (the Whatsapp folder in my case)
2. Set the option "Overwrite remote version" on file conflicts
3. replace file in that folder with new version

### Expected behaviour
Nextcloud should automatically overwrite the old file with the new one

### Actual behaviour
Nextcloud gives a notification for a File Conflict
After clicking on a notification I have to manually resolve the conflict

### Environment data
Android version: Android 10 / MIUI12  and Android9 / LineageOS16.0 

Device model: (POCO F2 Pro) and (Oneplus 3T)

Stock or customized system: Stock and Customized

Nextcloud app version: 3.13.1 RC1 / 1.13.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by phloose** [comment]
I can confirm this! I think it started happening two updates ago...

**Comment by computersalat** [comment]
same here...since update to 3.13.0 I am even not able to resolve conflict manually

**Comment by bestouff** [comment]
Failed uploads are piling up. If anyone has a workaround in the meantime please share !

**Comment by tobiasKaminsky** [comment]
This should be fixed with 3.13.1 RC1. You can try it via Google Play Beta version.
Stable 3.13 is planned for tomorrow.

**Comment by jeroen7s** [comment]
I don't think this is accurate as I definitely have this issue on 3.13.1 RC1

**Comment by tobiasKaminsky** [comment]
Is this also happening for new files?
Can you try to set the resolve strategy on this folder to something else, save, then set it back to overwrite?

**Comment by bestouff** [comment]
For me it happens for new files, and doing your manipulations doesn't change the behavior.

**Comment by smb500** [comment]
This error still exists with new files, as I posted here
https://github.com/nextcloud/android/issues/6963
Sorry, I didn't saw that thread here..

**Comment by smb500** [comment]
This error still exists with new files, as I posted here
https://github.com/nextcloud/android/issues/6963
Sorry, I didn't saw that thread here..

**Comment by smb500** [comment]
This error still exists with new files, as I posted here: https://github.com/nextcloud/android/issues/6963
Sorry, I didn't saw this thread here..

**Comment by Nodeswitch** [comment]
Can confirm this is happening with new files.

```
2020-09-17T00:10:33.927+0100;D;UploadFileOperation;normal upload
2020-09-17T00:10:33.930+0100;D;AdvancedSslSocketFactory;Creating SSL Socket with remote server:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@919d721
2020-09-17T00:10:33.930+0100;D;AdvancedSslSocketFactory; ... with connection timeout 0 and socket timeout 0
2020-09-17T00:10:33.931+0100;I;ServerNameIndicator;SSLSocket implementation: org.conscrypt.Java8EngineSocket
2020-09-17T00:10:33.931+0100;I;ServerNameIndicator;SNI done, hostname: server
2020-09-17T00:10:34.008+0100;D;UploadFileOperation;Checking name collision in server
2020-09-17T00:10:34.008+0100;D;OwnCloudClient #0;REQUEST HEAD /remote.php/webdav/InstantUpload/Camera/2020/09/IMG_20200916_141252.jpg
2020-09-17T00:10:34.008+0100;D;AdvancedSslSocketFactory;Creating SSL Socket with remote server:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@1c349a0
2020-09-17T00:10:34.008+0100;D;AdvancedSslSocketFactory; ... with connection timeout 50000 and socket timeout 50000
2020-09-17T00:10:34.009+0100;I;ServerNameIndicator;SNI done, hostname: server
2020-09-17T00:10:34.585+0100;D;ExistenceCheckRemoteOperation;Existence check for https://server/remote.php/webdav/InstantUpload/Camera/2020/09/IMG_20200916_141252.jpg targeting for  existence finished with HTTP status 404(FAIL)
2020-09-17T00:10:34.586+0100;D;UploadsStorageManager;QUERY: null ROWID: -1
2020-09-17T00:10:34.590+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 0, 100 rows total so far, last ID 841
2020-09-17T00:10:34.590+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 841
2020-09-17T00:10:34.594+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 1, 200 rows total so far, last ID 740
2020-09-17T00:10:34.594+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 740
2020-09-17T00:10:34.597+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 2, 300 rows total so far, last ID 640
2020-09-17T00:10:34.597+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 640
2020-09-17T00:10:34.600+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 3, 400 rows total so far, last ID 539
2020-09-17T00:10:34.600+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 539
2020-09-17T00:10:34.603+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 4, 500 rows total so far, last ID 438
2020-09-17T00:10:34.603+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 438
2020-09-17T00:10:34.605+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 5, 600 rows total so far, last ID 338
2020-09-17T00:10:34.605+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 338
2020-09-17T00:10:34.608+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 6, 700 rows total so far, last ID 238
2020-09-17T00:10:34.608+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 238
2020-09-17T00:10:34.611+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 7, 800 rows total so far, last ID 138
2020-09-17T00:10:34.611+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 138
2020-09-17T00:10:34.613+0100;V;UploadsStorageManager;getUploads() got 100 rows from page 8, 900 rows total so far, last ID 38
2020-09-17T00:10:34.613+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 38
2020-09-17T00:10:34.615+0100;V;UploadsStorageManager;getUploads() got 37 rows from page 9, 937 rows total so far, last ID 1
2020-09-17T00:10:34.615+0100;D;UploadsStorageManager;QUERY: _id < ? ROWID: 1
2020-09-17T00:10:34.617+0100;V;UploadsStorageManager;getUploads() got 0 rows from page 10, 937 rows total so far, last ID 1
2020-09-17T00:10:34.617+0100;V;UploadsStorageManager;getUploads() returning 937 (937) rows after reading 11 pages
2020-09-17T00:10:34.617+0100;V;UploadsStorageManager;Updating /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg with status=UPLOAD_IN_PROGRESS
2020-09-17T00:10:34.629+0100;D;UploadsStorageManager;updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg
2020-09-17T00:10:34.629+0100;D;UploadsStorageManager;notifyObserversNow
2020-09-17T00:10:34.630+0100;D;OwnCloudClient #0;REQUEST MKCOL /remote.php/dav/uploads/username/83d800a4fa19f41735fd2d33441eeb2e
2020-09-17T00:10:34.708+0100;D;OwnCloudClient #0;REQUEST PROPFIND /remote.php/dav/uploads/username/83d800a4fa19f41735fd2d33441eeb2e
2020-09-17T00:10:34.708+0100;D;AdvancedSslSocketFactory;Creating SSL Socket with remote server:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@b0f70a6
2020-09-17T00:10:34.708+0100;D;AdvancedSslSocketFactory; ... with connection timeout 5000 and socket timeout 40000
2020-09-17T00:10:34.709+0100;I;ServerNameIndicator;SNI done, hostname: server
2020-09-17T00:10:34.807+0100;D;OwnCloudClient #0;REQUEST MOVE /remote.php/dav/uploads/username/83d800a4fa19f41735fd2d33441eeb2e/.file
2020-09-17T00:10:34.961+0100;E;UploadFileOperation;Upload of /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg to /InstantUpload/Camera/2020/09/IMG_20200916_141252.jpg: Operation finished with HTTP status code 409 (fail)
2020-09-17T00:10:34.961+0100;D;UploadsStorageManager;updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=409, mHttpPhrase=Conflict, mException=null, mCode=CONFLICT, getLogMessage=Operation finished with HTTP status code 409 (fail)) upload: com.owncloud.android.operations.UploadFileOperation@4141800
2020-09-17T00:10:34.973+0100;V;UploadsStorageManager;Updating /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg with status:UPLOAD_FAILED and result:CONFLICT_ERROR (old:/storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg status:UPLOAD_IN_PROGRESS result:-1)
2020-09-17T00:10:34.973+0100;V;UploadsStorageManager;Updating /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg with status=UPLOAD_FAILED
2020-09-17T00:10:34.988+0100;D;UploadsStorageManager;updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20200916_141252.jpg
2020-09-17T00:10:34.988+0100;D;UploadsStorageManager;notifyObserversNow
2020-09-17T00:10:34.990+0100;D;FileUploader;NotifyUploadResult with resultCode: CONFLICT
2020-09-17T00:10:34.995+0100;D;FileUploader;Stopping command after id 1
2020-09-17T00:10:35.039+0100;V;UploadsStorageManager;Updating /storage/emulated/0/DCIM/Camera/IMG_20200916_140739.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20200916_140739.jpg status:UPLOAD_IN_PROGRESS result:-1)
2020-09-17T00:10:35.039+0100;V;UploadsStorageManager;Updating /storage/emulated/0/DCIM/Camera/IMG_20200916_140739.jpg with status=UPLOAD_IN_PROGRESS
```
Running 20200908 from F-Droid.

**Comment by jeroen7s** [comment]
Seems to be fixed for me after manually cancelling all pending conflicts (manually resolving wouldn't work, as they would re-appear as a conflict for some reason)

**Comment by smb500** [comment]
Sorry, not for me. I can (manually resolve and then) cancel all pending conflicts, but next day this error (that the resolved conflicts won't be cleared) is coming again with other files.

**Comment by computersalat** [comment]
The latest Versions of this app became ... sorry ... a complete mess.
3.13.1 is showing autoupload conflicts that need to be handled ` manually`. But even after manually resolving the conflicting file is shown as conflict ... the conflicting file is getting uploaded but still shown as conflicting file ... not good.
Instead of solving that issue you make it worse ...
with 3.13.0 you able to solve the conflict manually ... the file got uploaded and the conflict was solved.

I needed to re-add an account and reconfigure the whole `autoupload` again, cause there is nowhere an option to export or import the settings ... great job :+1: 
Now after having all that configured again the app is now trying to sync `ALL` files of the configured folder (in the past this used to be only new files being added to the folders) ...
- why am I not asked if I want to sync `ALL` or just new files coming ?
- why is the app so `dumb` and trying to `upload` everything instead of `syncing` ?
 ... ending up not being able to use the app cause of continously crashing and only showing `black screen` and showing the message `nexcloud is not responding` ...

From my point of view sync means:
- check if the file exists before uploading
not
- uploading and then showing conflict that file exists

**Comment by neurer** [comment]
Disabled sync for the specific folder. Updated from 3.13.1 RC1 to 3.13.1 via F-Droid -- changelog mentions "fix conflict handling on auto upload". Re-Enabled sync for the specific folder. Haven't had a single file upload conflict in the last three days.

**Comment by computersalat** [comment]
sync the WhatsApp database folder and you will have a conflict every morning cause of newly created msgstore.db.crypt12

**Comment by tobiasKaminsky** [comment]
> sync the WhatsApp database folder and you will have a conflict every morning cause of newly created msgstore.db.crypt12

I cannot verify this.
I tried this
- set up screenshot folder with "overwrite"
- take a screenshot -> uploads directly
- edit this screenshot 
- save -> uploads & overwrites

@computersalat are your settings correct?

@neurer says that it is working, or?

**Comment by neurer** [comment]
> @neurer says that it is working, or?

Correct. Everything is in sync as of now and file upload conflict hasn't appeared ever since.

**Comment by bestouff** [comment]
Strange. I have 3.13.1 from F-Droid and still the same sync troubles.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

Maybe this helps?

**Comment by bestouff** [comment]
Here you are:
[logcatOutput.txt](https://github.com/nextcloud/android/files/5454488/logcatOutput.txt)
I don't really know what to look for inside, only thing suspect I saw is this:
```
10-28 20:53:28.371  6624  6029 D ExistenceCheckRemoteOperation: Existence check for https://awak.mobi/nextcloud/remote.php/webdav/Call%20Recorder/2020-08-23%2014.59.45.ogg targeting for  existence finished with HTTP s
tatus 200
10-28 20:53:28.371  6624  6029 D UploadFileOperation: Name collision; asking the user what to do
10-28 20:53:28.372  6624  6029 E UploadFileOperation: Upload of /storage/emulated/0/Call Recorder/2020-08-23 14.59.45.ogg to /Call Recorder/2020-08-23 14.59.45.ogg: Synchronization conflict
10-28 20:53:28.373  6624  6029 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=null, mCode=SYNC_CONFLICT, getLogMessag
e=Synchronization conflict) upload: com.owncloud.android.operations.UploadFileOperation@eee3ba7
10-28 20:53:28.378  6624  6029 V UploadsStorageManager: Updating /storage/emulated/0/Call Recorder/2020-08-23 14.59.45.ogg with status:UPLOAD_FAILED and result:SYNC_CONFLICT (old:/storage/emulated/0/Call Recorder/2020
-08-23 14.59.45.ogg status:UPLOAD_IN_PROGRESS result:-1)
10-28 20:53:28.379  6624  6029 V UploadsStorageManager: Updating /storage/emulated/0/Call Recorder/2020-08-23 14.59.45.ogg with status=UPLOAD_FAILED
```

**Comment by tobiasKaminsky** [comment]
Hm. I added debug output which should be outputted when instant upload is running.
Have you added new files to all of those auto upload folders and gave me the entire logcat?
It must include "AutoUpload" and "Absolute path"…

**Comment by bestouff** [comment]
I don't really understand your question.  
I'm using my phone regularly, especially the "DCIM" and "Call Recorder" folders get new files. The file *do* get uploaded to my server, but the conflict notifications continue to pile up.  
What must include "AutoUpload" and "Absolute path" ? My settings ? The logcat command ? Something else ?

**Comment by tobiasKaminsky** [comment]
> What must include "AutoUpload" and "Absolute path" ?

I gave you a custom APK, or?
And logcat creates a text file, in this there must be above strings, then I can have a better understanding of what is going on.

**Comment by bestouff** [comment]
I'm sorry I must have missed something. Where is that custom APK ?

**Comment by tobiasKaminsky** [comment]
Ah, I mixed something up.
Let me have soon a more detailed look into it.

**Comment by tobiasKaminsky** [comment]
In 3.14.1 RC2 coming today there will hopefully be a fix. 
Can you try it and report back?

**Comment by bestouff** [comment]
Where can I find the apk (I'm on F-Droid, latest version available is 3.14.0) ?

**Comment by tobiasKaminsky** [comment]
On Fdroid it should be shown in versions in app details.
But currently it is not yet there. Fdroid always needs some more days…

**Comment by computersalat** [comment]
Maybe it is cause of Screenshot wants to get uploaded twice ?
First is uploaded ... second produces conflict
See Screenshot
![Screenshot_20201124-154144](https://user-images.githubusercontent.com/161880/100484559-3640af00-30fd-11eb-9893-2b342f6c16fd.jpg)

**Comment by bestouff** [comment]
Just installed 3.14.1rc2. It seems to work if I manually resolve old conflicts introduced by previous buggy versions - but as there are dozens of them it'll be a pain in the ###.
New files don't seem to produce conflicts so far.

**Comment by tobiasKaminsky** [comment]
> Should I leave the conflicts, hoping a new version will fix them automagically, or should I bite the bullet and fix everything manually ?

As this is hard to reproduce, please do not count on an automatic fix.
But you should be able to see all problematic uploads in upload view and then cancel them?

**Comment by UserX404** [comment]
Same problem here, uploading a 3.5GB file.
logcat:
```
02-19 19:56:42.873 28508 29758 D ChunkedFileUploadRemoteOperation: Upload of /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup to /Backup/file-2021-02-18-23-14-57.backup, chunk from 0000003788800000 to 0000003799039999 size: 10240000, HTTP result status 201
02-19 19:56:42.873 28508 29758 D OwnCloudClient #0: REQUEST PUT /nextcloud/remote.php/dav/uploads/user/99c94e232b4ca57121c066ede52c51d6/0000003799040000-0000003803672770
02-19 19:56:42.888   844 19341 I netd    : trafficSwapActiveStatsMap() <0.84ms>
02-19 19:56:42.895   844 19341 I netd    : tetherGetStats() <5.17ms>
02-19 19:56:42.943   844 19341 I netd    : bandwidthSetGlobalAlert(2097152) <0.37ms>
02-19 19:56:43.003  1032  4558 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xa
02-19 19:56:43.004  1422  1422 I cnss-daemon: nl80211 response handler invoked
02-19 19:56:43.004  1422  1422 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 10  received
02-19 19:56:43.007  4551  4551 I wpa_supplicant: wlan0: CTRL-EVENT-AVOID-FREQ ranges=2412-2452
02-19 19:56:43.009  4551  4551 I wpa_supplicant: wlan0: CTRL-EVENT-REGDOM-CHANGE init=DRIVER type=COUNTRY alpha2=AT
02-19 19:56:43.391 28508 29758 D ChunkedFileUploadRemoteOperation: Upload of /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup to /Backup/file-2021-02-18-23-14-57.backup, chunk from 0000003799040000 to 0000003803672770 size: 4632771, HTTP result status 201
02-19 19:56:43.394 28508 29758 D OwnCloudClient #0: REQUEST MOVE /nextcloud/remote.php/dav/uploads/user/99c94e232b4ca57121c066ede52c51d6/.file




02-19 19:57:23.530 28508 29758 E UploadFileOperation: Upload of /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup to /Backup/file-2021-02-18-23-14-57.backup: Socket timeout exception
02-19 19:57:23.530 28508 29758 E UploadFileOperation: java.net.SocketTimeoutException: Read timed out
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.net.SocketInputStream.socketRead0(Native Method)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:920)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:884)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.lib.resources.files.ChunkedFileUploadRemoteOperation.run(ChunkedFileUploadRemoteOperation.java:184)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.normalUpload(UploadFileOperation.java:830)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:432)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:85)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:633)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1404)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at android.os.Looper.loop(Looper.java:359)
02-19 19:57:23.530 28508 29758 E UploadFileOperation: 	at android.os.HandlerThread.run(HandlerThread.java:67)
02-19 19:57:23.532 28508 29758 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=java.net.SocketTimeoutException: Read timed out, mCode=TIMEOUT, getLogMessage=Socket timeout exception) upload: com.owncloud.android.operations.UploadFileOperation@a85006f
02-19 19:57:23.541 28508 29758 V UploadsStorageManager: Updating /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup status:UPLOAD_IN_PROGRESS result:-1)
02-19 19:57:23.542 28508 29758 V UploadsStorageManager: Updating /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup with status=UPLOAD_FAILED
02-19 19:57:23.560 28508 29758 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Files/Backups/file-2021-02-18-23-14-57.backup
02-19 19:57:23.560 28508 29758 D UploadsStorageManager: notifyObserversNow
02-19 19:57:23.562 28508 29758 D FileUploader: NotifyUploadResult with resultCode: TIMEOUT
02-19 19:57:23.576 28508 28508 D UploadListAdapter: loadUploadItemsFromDb
02-19 19:57:23.576 28508 29758 D FileUploader: Stopping command after id 10
02-19 19:57:23.584 28508 28550 D skia    : --- Failed to create image decoder with message 'unimplemented'
02-19 19:57:23.584 28508 28550 D skia    : --- Failed to create image decoder with message 'unimplemented'
02-19 19:57:23.591 28508 28508 D UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
02-19 19:57:23.591 28508 29758 V UploadsStorageManager: Updating /storage/emulated/0/Files/Backups/file-2021-02-19-17-28-38.backup with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/Files/Backups/file-2021-02-19-17-28-38.backup status:UPLOAD_IN_PROGRESS result:-1)
02-19 19:57:23.591 28508 29758 V UploadsStorageManager: Updating /storage/emulated/0/Files/Backups/file-2021-02-19-17-28-38.backup with status=UPLOAD_IN_PROGRESS
02-19 19:57:23.602 28508 29758 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Files/Backups/file-2021-02-19-17-28-38.backup
02-19 19:57:23.602 28508 29758 D UploadsStorageManager: notifyObserversNow
```

Where does the 50sec timeout comes from?

**Comment by jeroen7s** [comment]
Is this bug still relevant? I no longer have this issue.

**Comment by ColinFinck** [comment]
@jeroen7s @smb500 @tobiasKaminsky I still have this problem with Nextcloud App 3.19.1 and Nextcloud Server 23.0.2. Conflict prompts with overwrite requests are piling up despite having set the auto-upload to overwrite remote files automatically.

I didn't want to open a new issue for that, as I could only contribute the same report and screenshots.
But I also don't have permissions to reopen this bug. Someone please do that.

I'm open to contribute logs or try out beta versions if you tell me what you need.

**Comment by ColinFinck** [comment]
Let me know what you need to debug this issue further. It still happens for me every day..

**Comment by joshtrichards** [comment]
@ColinFinck As the original reporter's matter is addressed, the root cause of anything you're experiencing is different so please create a dedicated issue for it. Thanks!
