### ISSUE TITLE
Nightly 20170301: AutoUpload issue (other folder)

### ISSUE THREAD

**Issue by ralftar** [nextcloud/android#731]
### Actual behaviour
Files stored in snapchat folder won't auto-upload at all.

As many others, I have been struggling with the auto upload for a while. Testing with the nightly build of 20170301 with Android 7 (same result with android 6); I am concluding that auto upload for screenshots works fine, auto upload from camera work doubtfully fine (have not been able to reproduce faults systematically, but I have a hunch that it have failed). Auto-upload from other folder (i.e) snapchat is broken (hence this report).

### Expected behaviour
Auto upload from all defined folders should work, including snapchat folder.
 
### Steps to reproduce
1. Open/install Snapchat
2. Configure it to save "memory" pictures locally as aswell
3. Configure NC to auto upload from local snapchat folder (the folder with is latest pictures is visible in the NC setting)
4. Save a memory in snapchat (which stores the poto locally)
5. No auto-upload :(

### Environment data
Android version: 7.0 
Device model: Samsung Galaxy S7
Nextcloud app version: Nightly 20170301
Nextcloud server version:  11.0.2

**Comment by Bullnados** [comment]
Have u tried 1.4.2 RC4? It is newer than nightly

**Comment by OlivierS1** [comment]
There are folders that do not work at all and may very well be due to the mechanism used to write to the relevant folders by the other applications.
For instance, I have WMU application from Nikon to download pictures from my SLR camera. The photo folder which has been marked for upload does appear in the Auto upload settings but upload never take place.
I suspect Nextcloud app does get the triggering event required to start the upload.

**Comment by AndyScherzinger** [comment]
@OlivierS1 - @mario knows best since he rewrote the auto upload mechanism so he can say how the mechanism works (I just wrote the original UI with the initial release of the feature).

**Comment by ralftar** [comment]
@Bullnados Yes, same issue with 1.4.2 RC4.

**Comment by mario** [comment]
Unfortunately I do not know why Snapchat fails, and I don't use Snapchat so can't test. The basics of how the mechanism works:

- list a directory
- list it again
- do a diff
- if there's a difference, upload those files

So basically, it should work everywhere. If anything, it's known to fail on various 3rd party roms where we might get denied access to the filesystem.
In order to fix Snapchat or your other issues, if you know how to install Android studio, Git, all the SDKs + Teamviewer and would let me connect to your machine (with the phone connected via USB) we could try debugging it together just like I did with @jasonbayton (remind me the tool we used btw?)

Thanks!

**Comment by ralftar** [comment]
@mario I will be happy to assist, and are now up and running. Please let me know when we can schedule a session.

**Comment by jasonbayton** [comment]
@mario team viewer in presentation mode :)

**Comment by mario** [comment]
I meant that tool to show your phone screen dude :p

**Comment by jasonbayton** [comment]
Ah Vysor. You weren't clear :p

**Comment by ralftar** [comment]
All set, just let me know when you are ready @mario

**Comment by mario** [comment]
@ralftar what timezone are you and what is better for you, before noon, or afternoon? I can do Monday.

**Comment by mario** [comment]
(if you want, you can mail me at mario@nextcloud.com)

Thanks for the help in advance! :)

**Comment by mario** [comment]
Will be late a bit, urgent personal situation

**Comment by ralftar** [comment]
Is this resolved in the last build @mario ? :)

**Comment by mario** [comment]
It's fixed in master. Dunno if we made a build out of it yet.

**Comment by AndyScherzinger** [comment]
We didn't, since master and beta due to the latest feature merges now different quite a bit and have conflicts, so an auto merge isn't happening. Will have to see when @tobiasKaminsky is back. My guess would be with all the structural changes that the beta needs to be rebuild from scratch.

**Comment by ralftar** [comment]
Ok. I suppose this issue could be marked as resolved anyways. 

..perhaps there should be a cleanup in other issues' statuses as well *cough*

**Comment by AndyScherzinger** [comment]
Well, as far as I understand the issue isn't solved since the issue targets the nightlies where this is still present, so the status remains open until an new nightly has been published with the fix, so I am unsure which issues status should be updated then :)

**Comment by ralftar** [comment]
It targets one specific nightly build for reference.
Depends on you define the bug as solved once a fix is committed, or once it is built. I would suggest the first one, but this is not my fight, just a friendly suggestion.

**Comment by AndyScherzinger** [comment]
Not fighting at all @ralftar and yes there is a fix commited and it has bene merged to master, but it hasn't been merge to beta, so even a built won't give you a fix, someone still has to do a manual merge to the nightly branch, that's why I would suggest to leave it open, so we know there is still a todo from the dev perspective :)

**Comment by ralftar** [comment]
All good 👍
