### ISSUE TITLE
Auto-uploaded files that are moved to app folder are deleted from local storage the next time the folder is viewed in the app

### ISSUE THREAD

**Issue by DoctorMcKay** [nextcloud/android#735]
### Actual behaviour
After images are taken and auto-uploaded, they are moved to the app folder as expected. However, the next time the folder containing those images are viewed in the Nextcloud app, the images are deleted.

### Expected behaviour
The images should not be deleted and should appear with a green checkmark as with all other locally-available files.
 
### Steps to reproduce
1. Enable auto upload for e.g. the camera
2. Change "Original file will be..." to "moved to app folder"
3. Take a picture
4. View the upload subfolder of the app folder in a file explorer and notice that the image has been moved there
5. Open the upload folder in the app and notice that the newly-uploaded image has no green checkmark
6. View the upload subfolder of the app folder in a file explorer again and notice that the image is gone

### Environment data
Android version: 7.1.1

Device model: Pixel XL

Stock or customized system: Stock

Nextcloud app version: 1.4.2 RC4

Nextcloud server version: 11.0.1

**Comment by mario** [comment]
Thanks for the report. 

@AndyScherzinger think you can test this?

**Comment by AndyScherzinger** [comment]
@mario @DoctorMcKay  just tested 1.4.2 RC4 and server 11.0.1 and the files stay in the app folder, Runnign OP3T Android 7

**Comment by Bullnados** [comment]
I can confirm that bug with LG G4 6.0 stock
Take a picture-->Pic is in standard folder 
Pic get uploaded--->Pic isn't anymore in standard camera folder
Pic should be accesable via file explorer, but there is no pic.
If u open the app u can see the pic in your AutoUpload folder

It seems that the file will be deleated from sdcard and only availible "online". I think @DoctorMcKay will say, that the images should stay offline after moving to the AutoUpload folder

**Comment by AndyScherzinger** [comment]
@Bullnados are you also using the "moved to app folder" option?

**Comment by Bullnados** [comment]
yes

**Comment by hornowitz** [comment]
I just wanted to say, that I can confirm this bug as well. "Moved to app folder" selected and my Android device (6.0.1), Nextcloud App 1.4.2 and Nextcloud server 11.0.1.
Everything is going to be deleted after sucessfully uploaded.

**Comment by tobiasKaminsky** [comment]
This is fixed in current master and will be available in 1.5.0.
Please feel free to reopen if it happens again.

**Comment by realaerosol** [comment]
same problem here.

Device model:
Redmi 4x

Stock or customized system:
LineageOS

Nextcloud app version: 3.0.0

Nextcloud server version: 13.0.0

**Comment by CNeutron** [comment]
I have the same bug. My setup is a Sony X Compact with android 7.1
The Nextcloud App Data is on the SD. The picked up Pictures are on internal (i do a rename before to avoid the overwriting Problem, becaus of the strange behaviour of Sony Camera App)

As soon as the Picture is uploaded it gets moved correctly into the App Data Folder (checking with Total Commander).
If I go into the Folder in the Nextcloud App, the File gets deleted on the Filesystem. After a synchronize it gets downloaded, and appears in the Filesystem again.

**Comment by DoctorMcKay** [comment]
This is still happening for me, now on a Galaxy S9+. App version 3.0.3.

**Comment by illBeRespawned** [comment]
I think I have the same issue on the Fairphone 2 (18.04.1)

all pictures were moved to the app directory after that they were 0KB big and where also uploaded like that.

I rooted the phone and tried diskdigger which comes up with none of the missing pictures.

This is a terrible bug made me loose all of my holiday pictures and so far no luck in recovering them.

**Comment by ftoral** [comment]
I came from issue #2131 ([my comment](https://github.com/nextcloud/android/issues/2131#issuecomment-414832109)) and it seems that it is not really resolved. Maybe this should be reopened referencing the other duplicated issues ?
