### ISSUE TITLE
ipv6 not reachable, app not fallback ipv4

### ISSUE THREAD

**Issue by flob82** [nextcloud/android#7400]
Hello

I'm just encountered this issue because my server lose ipv6.
Logcat only show attempts to connect in ipv6
Nextcloud work fine in ipv4.

### Steps to reproduce
1. my server lose ipv6
2. ipv4 and nextcloud server still available

### Expected behaviour
- App should fallback ipv4 if ipv6 is unreachable

### Actual behaviour
- App say "network unavailable" if i'm already connect to my account
or say "host not find" if i try to connect new account

### Can you reproduce this problem on https://try.nextcloud.com?
No

### Environment data
Android version: Lineage 17.1 (android 10)

Device model: Oneplus 2 : A2003

Stock or customized system:

Nextcloud app version: 3.14.0

Nextcloud server version: 20.0.2

Reverse proxy: No

### Logs
Only shows attempt in ipv6

#### Web server error log
No errors because not trying to serve ipv4

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky about the ipv6/4 issue reported for 3.14.0

**Comment by flob82** [comment]
Just for info since this bug i've recovered my ipv6 and all is fine. But i want to share this.
Maybe you can test this, with a nextcloud server configure both ipv4 and ipv6
and disable ipv6 on server side.

**Comment by tobiasKaminsky** [comment]
So it is
- server supports v4/v6
- install & connect app (how does we know that it prefers v6?)
- disable v6 (how?)
- app does not work, but should fall back to v4 again
- enable v6 again, app works again

**Comment by flob82** [comment]
hi @tobiasKaminsky 

> So it is
> 
>     * server supports v4/v6

yes he listen in v4 & v6, DNS records are valid (A, AAAA)

>     * install & connect app (how does we know that it prefers v6?)

before this issue i don't care this but after some searches and logcat
my app prefer v6 only and doesn't fallback v4 in wifi (configure v4 + v6)
When i switch on LTE (ipv4 only) the app works in v4

>     * disable v6 (how?)
maybe trying to shutdown the v6 interface
In my side my server get the old IPV6 (my ISP change the IPV6) then i lose ipv6 connection

>     * app does not work, but should fall back to v4 again
I think if your mobile receive v4 & v6, v6 is prefered.

>     * enable v6 again, app works again
Exactly since i've configured my new IPV6 on the server side all is fine

Thanks

**Comment by flob82** [comment]
Just try this on my server : 
`sysctl -w net.ipv6.conf.all.disable_ipv6=1`
My app say : "server unavailable"
And
`sysctl -w net.ipv6.conf.all.disable_ipv6=0`
`service networking restart`
And the app connect to the server in V6

**Comment by expoli** [comment]
The app can connect nextcloud server over ipv6?
My nextcloud server run on ipv6, I can connect it use chrome, but when I try use the app connect it, it says that 

![Screenshot_2020-11-26-11-21-53-122_com nextcloud client](https://user-images.githubusercontent.com/31023767/100304390-9d654300-2fd9-11eb-92bf-beb97a4d5d50.jpg)

But I can connect it use web, I can't found the app's log, so I don't know what happened.

The domain name only Parse ipv6 address

![Screenshot_2020-11-26-11-24-01-198_com android chrome](https://user-images.githubusercontent.com/31023767/100304608-0ea4f600-2fda-11eb-88ef-f1478d6d8b1e.jpg)

**Comment by Weasy666** [comment]
I can confirm this behaviour. The app does not seem to fallback to IPv4, it just tries to connect to IPv6 and stops working after the connection attempt times out.

**Comment by tobiasKaminsky** [comment]
Yes, same like it would do if there is only v4, which is not reachable.
Not perfect, sure, but real problem is that there is a v6 address which does not work.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this issue keeps pilling up and while you are absolutely right the issue remains that most people with this issue seem to not be able to correct their ipv6 setup ("work in firefox"...) So maybe if ipv6 "doesn't work for whatever reason" we should try to fallback to ipv4 (if we can detect this).

**Comment by flob82** [comment]
sure but the app should not try v4 if v6 is not reachable and try v6 if v4 not reachable ?

**Comment by tobiasKaminsky** [comment]
> seem to not be able to correct their ipv6 setup ("work in firefox"...)

I rather suspect that Firefox either has a fallback or first uses v4.

**Comment by tobiasKaminsky** [comment]
> So maybe if ipv6 "doesn't work for whatever reason" we should try to fallback to ipv4 (if we can detect this).

No real idea how to do it: 
Do we want to try v4 after x seconds of v6, but what if server is just slow?
And then we have this for each and every request…

Or we would have to store preferred v4/v6 and test it from time to time, which is a giant overhead code-wise.

So I think that if a server is available via v6 via DNS, then it should also work properly.
Everything else is fighting symptoms, but not the real cause.

E.g. on email sending, there are also different protocols / ports (543, 999) and there user also  needs to pick the right one, and client app does not try to be smart and uses a different available one.
(maybe not the best example…)

**Comment by AndyScherzinger** [comment]
> I rather suspect that Firefox either has a fallback or first uses v4.

Very likely. The problem is the view/experience of the user as in: "work with any Nextcloud client except for the Android App"

**Comment by Weasy666** [comment]
How about a setting option that lets a user specifiy which IP version should be used?

**Comment by flob82** [comment]
i will see 
test v6 -> timeout 3 sec -> test v4 if exists timeout 3 sec -> and so "No network connection"

**Comment by NotSoImportant** [comment]
> this issue keeps pilling up and while you are absolutely right the issue remains that most people with this issue seem to not be able to correct their ipv6 setup

Very true. Many people are using a hosted version of nextcloud and cannot influence their server ipv6 setup. So please fix this. Otherwise app is unusable.

**Comment by NotSoImportant** [comment]
By the way: it's not only working in Firefox, but all modern browsers I am aware of. Some DAV clients seem to have a problem from time to time (probably the same one). But they manage with non-frequent retries without crashing or crash-looping.

**Comment by it25fg** [comment]
Nextcloud tries v6 even if there's only a FE80: address at the WIFI interface -- is this intentional? From my understanding, it's unlikely to reach DNS or any other host via such an address. (As always: please correct me if I'm wrong.)

**Comment by tobiasKaminsky** [comment]
We use 
https://github.com/nextcloud/android-library/blob/c333b824b42109c6e07d9d9c46f9b7d3045b2ebc/src/main/java/com/owncloud/android/lib/common/network/AdvancedSslSocketFactory.java#L191-L193

and

https://github.com/nextcloud/android-library/blob/c333b824b42109c6e07d9d9c46f9b7d3045b2ebc/src/main/java/com/nextcloud/common/IPV6PreferringDNS.java#L17

Bothg should not use "any" IPv6, but only those IPv6 that are really associated to the hostname.

**Comment by it25fg** [comment]
How can I verify this "only those IPv6 that are really associated to the hostname"?

I set up a Wifi hotspot that definitely only announces v4, but this is the result:
```
root@xcover3velte:/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: umts_dm0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ppp 
3: rmnet0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ppp 
4: rmnet1: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ppp 
5: rmnet2: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ppp 
6: rmnet3: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ppp 
7: sit0: <NOARP> mtu 1480 qdisc noop state DOWN 
    link/sit 0.0.0.0 brd 0.0.0.0
8: ip6tnl0: <NOARP> mtu 1452 qdisc noop state DOWN 
    link/tunnel6 :: brd ::
9: p2p0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state DORMANT qlen 1000
    link/ether 46:78:3e:2e:4d:6e brd ff:ff:ff:ff:ff:ff
10: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 44:78:3e:2e:4d:6e brd ff:ff:ff:ff:ff:ff
    inet 172.25.25.137/24 brd 172.25.25.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::4678:3eff:fe2e:4d6e/64 scope link 
       valid_lft forever preferred_lft forever
```
and as soon as it is connected, the crash loop begins.
It did not help to manually issue
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
```
as mentioned earlier, and deleting the v6 address
```
ip -6 addr del fe80::4678:3eff:fe2e:4d6e/64 dev wlan0
```
made it vanish from 'ip a' list, but the loop didn't stop either.

What are my options now?

**Comment by flob82** [comment]
Hello

You haven't ipv6 link in your config here.
fe80:: is local.

You can check dig [your_domain_name] ANY @DNS_SERVER
or simply dig [your_domain_name] AAAA

If you've configured an ipv6 you must see it.
This can be the problem if your domain name have ipv6 and your server doesn't respond in ipv6.

**Comment by it25fg** [comment]
> You haven't ipv6 link in your config here.
> fe80:: is local.

Exactly. I already said that in https://github.com/nextcloud/android/issues/7400#issuecomment-789164120. And the app is unable to recognize that this is not a valid v6 connection to the internet.

> This can be the problem if your domain name have ipv6 and your server doesn't respond in ipv6.

DNS can always return v6 addresses for a server. This does not necessarily mean that my device must have a v6-capable connection to that server. The app connects to the v6 address even if (1) there is no v6 connection to the internet and (2) the DNS query surely has returned a v4 address too.

And what now? Shall I set up a hotspot with a DNS proxy that filters out any AAAA responses?

**Comment by flob82** [comment]
> Exactly. I already said that in [#7400 (comment)](https://github.com/nextcloud/android/issues/7400#issuecomment-789164120). And the app is unable to recognize that this is not a valid v6 connection to the internet.

No the app search for Ipv4/Ipv6 corresponding to your dns entry not your server config.

> DNS can always return v6 addresses for a server. This does not necessarily mean that my device must have a v6-capable connection to that server. The app connects to the v6 address even if (1) there is no v6 connection to the internet and (2) the DNS query surely has returned a v4 address too.

hmmm i'm agree with @tobiasKaminsky if you configured an ipv6 for your domain you need to configure it properly.
the problem in this issue is just if we have a temporaly ipv6 connectivity issue the app need to switch in ipv4

> And what now? Shall I set up a hotspot with a DNS proxy that filters out any AAAA responses?

If i understand your problem you need to configure an ipv6 on server side or remove DNS entry for IPV6 if u don't plan to configure it.

**Comment by szaimen** [comment]
I second what @flob82 said.
So the easiest way to fix this is to remove the AAAA record from your domain.

**Comment by it25fg** [comment]
> If i understand your problem

Not really. Its about: a server that is reachable via v4 and v6, and **one** app on **one** device that is sometimes not connected via v6. I don't have to 'fix' my server if only this **one** out of countless apps fails to recognize that it currently can't use v6.

Sorry if it sounds rude, but it's definitely not me who has to fix that. It is a normal situation that servers are reachable via different protocols, and it is a normal situation that a client sometimes cannot use all protocols, so it has to be capable of recognizing this, and to act accordingly.

**Comment by flob82** [comment]
OK I did not encounter this problem in my tests, if my device is only v4, the app connect well. (with a server with v4 only and v4/v6 configured). Can't help you anymore

**Comment by it25fg** [comment]
> if my device is only v4, the app connect well

How do you get your device to be v4-only? In https://github.com/nextcloud/android/issues/7400#issuecomment-732172396, you mentioned LTE: yes one can set a preference in the APN settings of mobile data. My problem is that for WIFI there's no such preference, and it always assigns this FE80: address. Whatever I do, I don't get my device to be v4-only. If someone knows better, please help.

> Can't help you anymore

Your help was the clue about DNS being a contributing factor here. Let's hope our vague assumptions can shed some light onto the issue, and that somebody™ can *really fix* it.

**Comment by szaimen** [comment]
@it25fg what does `dig [your_domain_name] AAAA` return? Does it return the public ip address of your server/network or e.g. a local IPv6 address?

**Comment by it25fg** [comment]
> @it25fg what does `dig [your_domain_name] AAAA` return? Does it return the public ip address of your server/network or e.g. a local IPv6 address?

My client connects to 10 different domains. Five of them have an AAAA record. None of the addresses starts with FE80.

I'd like to check this on the phone too (ADB), but there's no dig and no nslookup. While I'm connected to WIFI (without v6 connectivity) ping uses the v4 address and succeeds, and ping6 returns 'network is unreachable'. Only the NC app does not recognize that it makes no sense to try v6 in this situation.

**Comment by szaimen** [comment]
you could install the [termux app](https://f-droid.org/en/packages/com.termux/) and try it for the domain in focus there.

**Comment by it25fg** [comment]
@szaimen Many thanks, but this won't help here: while connected, the NC app is in a crash loop that makes it impossible to do anything at the surface. (only pull the status bar and switch network off) That's why I'm using ADB -- it's the only thing that works undisturbed from the crash.

**Comment by szaimen** [comment]
But what does the mentioned command return if you run it via termux?

**Comment by it25fg** [comment]
Let's see how I get it installed (you know: connect to network -> crash loop). Please don't ask -- currently I'm tempted to throw this app where it belongs! Yes I know, the risk is with me if I use a DEV version, I fully understand it, and I wouldn't ever entrust it with any valuable data. But this... Please bear with me, I'll be back when I can grab some new hope; for now it's exhausted.

**Comment by szaimen** [comment]
Termux is no addition for the Nextcloud Android app but a standalone android app so you should be able to run the command in the termux app without having to go through the Nextcloud app.

**Comment by it25fg** [comment]
Imagine: you turn network on, and in a second, the NC app pops up showing the 'oooh sorry, we crashed, would you like to submit a bug report' screen, but before you even can tap YES, the Android crash dialog appears 'an application has crashed -- we will restart it' and one second later the game starts over -- no chance to do anything on the surface, it loops and loops and loops. Do you understand? No chance to install an app. You can pull the status bar and switch network off. Yeah. And how to install an app without network? Yes I know, download it manually, upload it to the phone via ADB, open the installer in a file mananger... Too tired to invest more time today. Nevertheless, thank you for your efforts, you only want to help.

**Comment by szaimen** [comment]
And you are not even able to stop or uninstall the Nextcloud app?

**Comment by szaimen** [comment]
Could you maybe run the command from a laptop in the same network if your phone doesn't want to?

**Comment by szaimen** [comment]
@it25fg did you see [this](https://twitter.com/Android/status/1374514715251023880)? maybe this is the reason for your crashes...

**Comment by jonim8or** [comment]
I created the new issue 8269, but probably it is better to continue the talk in this thread as it already contains some useful responses. 
I'll try to answer the questions to help solve the issue. To be able to use my phone again I have enabled airplane mode (to stop the popups), and then uninstalled nextcloud. I've also reinstalled the app, but now I can't even connect any more, probably also due to ipv6. (I can login, then the phone asks me to confirm, but that request is never completed).
For now I got my phone working again by stepping out of the nextcloud preview program, so that I don't have *3.16.0 rc2* but *3.15.1*, and now it works like a charm again.

I believe there are two issues in this topic that need to be discussed.

## Failure makes phone unusable

The way the app responds to the failure, is very serious, as it makes the phone unusable. Only technical minds come up with the idea to stop the popups by switching to airplane mode. I think these questions should be raised:

- Is it helpful to immediately try again? other options include trying again after longer and longer intervals, or asking the user if he wants to try again or cancel
- Is this notification so important that it should popup over other apps? or is it fine to just show the notification in the nextcloud app itself?

## Ipv6 usage

In my case the problem is probably that my home internet (where I run my self-hosted nextcloud) only gets an ipv4 address. (my internet provider is still in the process of switching to ipv6) When I visit https://whatismyipaddress.com/ it only shows an ipv4 address. Therefore my self-hosted nextcloud only gets an ipv4 address, and there's nothing I can do about it (except maybe switching internet provider). 
- Could nextcloud client default to ipv6 but fallback to ipv4 if ipv6 fails?
- Could nextcloud client have an option to configure it to only use ipv4?

**Comment by szaimen** [comment]
@jonim8or what does `dig [your_domain_name] AAAA` return? Does it return the public ip address of your server/network or e.g. a local IPv6 address?

**Comment by jonim8or** [comment]
Assuming it does not matter from which device I call it (because it is a general dns lookup)
It does not return anything. My dns record only has an ipv4 address, because I couldn't add an AAAA record. And I couldn't add an AAAA record, because my home router (which gives access to my nextcloud) does not get an ipv6 address from my internet provider.

**Comment by szaimen** [comment]
Hm... Strange. I have excactly the same configuration (the command doesn't return anything, so the AAAA record isn't set) and the Android app connects without any problem for me.

**Comment by jonim8or** [comment]
For me the 3.15.1 version works fine, but the 3.16 rc2 does not. Which
version do you use?

**Comment by szaimen** [comment]
I am using the same version...

**Comment by AkechiShiro** [comment]
Hi, I'm using a brand-new phone and I seem to face this issue, I have termux installed with dnsutils and using logcat I've seen that Nextcloud uses the IPv6 to resolve the server.

My server has a specific setup that allows IPv4 or IPv6 devices to resolve it.

The problem is that the Nextcloud android app is trying to use the IPv6 and that doesn't work. The connection timeouts because of an issue in my local network that I couldn't solve.

But the application should fallback to IPv4 to join the server (since that works inside the Chrome application on my Android device) instead it's just not working in the Nextcloud app and that is the issue described here I think.

`dig [my_domain_name] +short AAAA`

Resolves to an IPv6, but the `ping6` command timeouts.

Using `ping [my_domain_name]` works fine as expected.

I can give more logs if that helps diagnose this issue and allow a fix of this inside the app in a new release.

**Comment by jonim8or** [comment]
Lahfa, which version of the nextcloud android client are you using? I'm
asking because my issue only happens with the release candidate, and not
with the normal 3.15.1 release.

And which part is not working for you? Syncing files? Or logging in? And
does your phone also get in an infinite loop of popup error messages?

**Comment by AkechiShiro** [comment]
I'm using 3.15.1 (I edited the last comment I made) but I have no endless crashes on my Android phone, the only errors that gets thrown are in the logcat shows Java code throwing a socket timeout (to the IPv6 of my server) and the app is constantly charging, my issue is why the app doesn't fallback to IPv4 since IPv4 works.

I could connect because before IPv6 worked for me (when I logged in) and now isn't working, so I can't access/view the files (retrieve the list of files inside the server). No communication with the server is possible due to IPv6 malfunctioning and the app does not fall back to IPv4, this is the issue that I'm facing.

**Comment by storm1er** [comment]
Hi,

Just installed nextcloud 21, self host, ipv4 only (no choice),
this issue is live since 6 months and has not been fixed yet? :(

I'll try to take a look at it, but god damn, what a failure to see this kind of issue staling...

Does anyone have a clue if it's related to recent changes about ipv6 like this https://github.com/nextcloud/android/pull/6902?

**Comment by AkechiShiro** [comment]
Hi, @storm1er, I'm actually also astonished by the amount of time this issue has been open for, maybe the fix isn't simple (I need to take a look at the code), did you have time to take a quick look at it?

I'm going to try and take a look as well, maybe work on a new PR even because this issue is real a pain for me to deal with.

**Comment by storm1er** [comment]
As it was a family goal, I ended up setting up a VPN with ipv6.

I didn't had time to look at the code yet :(

**Comment by szaimen** [comment]
Just FYI: I suppose this is the PR that implemented prefering IPv6 over IPv4: https://github.com/nextcloud/android-library/pull/503

**Comment by jonim8or** [comment]
For me the problem was fixed in  [nextcloud/android] [3.16.0 rc2] failure
to upload files makes phone unusable (#8269)

I tried the dev build from that topic and that worked for me

**Comment by Alex98234** [comment]
Same issue here, while other apps with nextcloud integration work flawless, such KeePass2Android.

Nextcloud app version: 3.16.1 (Google Play Store)
Android version: LineageOS 18.1(lineage_beryllium-userdebug 11 RQ2A.210505.003 8c426fef0)

**Comment by mburnicki** [comment]
Similar issue here.
Started my setup a long time ago, running NC server on my local intranet, behind a NAT router (Fritzbox). External IPv4 address resolved via DynDNS, with an unusual port at the outside, which is forwarded to the standard https port 443 at the server on the intranet.

All this worked well (and still does) as long as the IPv4 address with the unusual port is used from the outside world, but if my router configures an IPv6 address in DynDNS, the Android App only seems to try that one, and fails, also because port forwarding from an unusual port to 443 doesn't seem to be possible with IPv6.

Normal web access via a browser using an URL with the DynDNS address and the unusual port still works as expected.

It would be really helpful if the client would try to use IPv4 if IPv6 is unable to reach the server.

**Comment by AkechiShiro** [comment]
I've taken an initial look at the current code of the Android app, it seems a PR to the Android app repo wouldn't be useful to fix anything, @szaimen is correct I think (thanks btw for your precious help !). 

I think that most of the code handling the DNS resolving has been moved to the [nextcloud/android-library](https://github.com/nextcloud/android-library) and is not inside this repo anymore, if anyone has taken a look and could confirm or refute my statement.

I highly think a PR in the android-library is needed to solve this issue here.

**Comment by KeenMaron** [comment]
same issue. Only IPV4 is active. I can access nextcloud with browser or fileexplorer with webdav over the internet. The nextcloud app can't connect in any case.

**Comment by wedontneedme** [comment]
Wow, I really cannot understand why this is still not fixed! The problem is documented, lots of people cannot change anything about it beside using an outdated android-app, while everything else (iOS, webdav, etc.) is working flawlessly? Why is this not a high priority thing?

**Comment by gerstrong** [comment]
Same problem Here, disappointing...

**Comment by AkechiShiro** [comment]
I've tried to work on a quick fix inside the android-library handling the DNS request along with the priority given to IPv6, but I ended up in a dead end with no progress so far. 

Recently, I noticed this issue is gone from my device, is this the case for everyone else ? 
I'm still using Nextcloud app 3.16.1 from the Google Play Store, someone reported this issue was still happening on June 04, 2021.

The only change I noticed so far could be a server update ? 

Nextcloud server version : 21.0.2.

**Comment by mepreston** [comment]
still fails in 3.17 client.  My server version is 22.1.0.

**Comment by TimoRoth** [comment]
Following situation for me: Mobile Network has IPv6, local WiFi does not.
I changed my Nextcloud Servers domain to be IPv4 only, so it has no IPv6 address in DNS.

However, now the App does the following:
 java.net.ConnectException: failed to connect to nextcloud4.myserver.tld/64:ff9b::88f3:4a55 (port 443) from /2001:db8:ad:0:ff:: (port 37693) after 50000ms: isConnected failed: ENETUNREACH (Network is unreachable)

It seems to still try really hard to connect to my IPv4 only Domain via an IPv6 Socket, and in turn fails very badly.
As it stands right now, the Nextcloud App is completely unuseable on any IPv4 Only WLAN Network right now.
It spams my notifications with hundreds of errors per minute.

**Comment by Alex98234** [comment]
So far the only way to mitigate this issue was to remove the domain AAAA record entirely. With only a A record, only a IPv4 adress is available the the connection does not fail all the time.

2021 and I have to disable IPv6, this is strange.

**Comment by TimoRoth** [comment]
That's exactly what I tried, and it did not work, but instead lead to above mentioned error.

**Comment by mepreston** [comment]
seriously firefox mobile has never had an issue connecting my nextcloud server but  this client does. if they can do it way can't you?

**Comment by BtbN** [comment]
Some more input on this: I just discovered that my mobile ISP uses NAT64 for IPv4 connectivity.
So if the app tries to resolve a IPv4 only domain, it gets back a IP in the form of "64:ff9b::...", which is a NAT64 translated IPv4 address.
This IP works on my mobile ISPs network. But when I connect to WiFi, it stops working for obvious reasons.

But even after hours being connected to my home WiFi, nextcloud, and only nextcloud, insists on using that NAT64 IP, and keeps failing.
If I disable mobile data and reboot the device, the nextcloud app works just fine.
This is obviously unacceptable and needs to be finally fixed.
Something in the nextcloud app caches the DNS response WAY to aggressively (basically permanently).

**Comment by danbulant** [comment]
Nextcloud app needs to fallback to ipv4 when it can't reach server using IPv6. Sucks that every other client does it. 

My ISP doesn't support IPv6 yet, and I use cloudflare for the cloud. This results in dns returning AAAA records and app trying to reach those, but failing because I don't have IPv6 address.

When I turn off cloudflare proxy it works, but then I have no https (can be fixed but it's hassle for me) and I lose some features. Not to mention I'm not protected against ddos and similar. When I don't have enabled IPv6, the dns simply doesn't return AAAA records in which case it needs to use ipv4 anyway.

**Comment by larena1** [comment]
Same issue here. Underlying OkHttp library apparently does not check whether IPv6 is reachable and just picks the first resolved IP to connect to.

https://github.com/nextcloud/android-library/pull/503 Why wasn't this PR reverted already more than a year after this issue was opened?

**Comment by mepreston** [comment]
these three issues all seem to be related. 
 prefer IPV6 addresses if available #503 
 ipv6 not reachable, app not fallback ipv4 #7400 
 Connection fails if ipv6 connection do not work properly #7839 

 The two open "bug"  have been opened more than an year 
and yet this issue still have not been resolved.  Is anyone 
doing project management for this product?  this is giving
NC server a black eye when the mobile client can't connect .
https://github.com/nextcloud/android/issues/7400
https://github.com/nextcloud/android/issues/7839

**Comment by larena1** [comment]
@mepreston I'm also shocked. Having both an A and AAAA record on your server is pretty common these days. An app that fails to connect from a network with only IPv4 available because it'll always try to connect to the IPv6 address of the server is absolutely not common though. Even more when that was reported a year ago already.

**Comment by BtbN** [comment]
I'm having the issue despite explicitly using a domain which only has an A-Record.

What's happening for me is my mobile ISP uses an IPv6-Only Setup, with NAT64. So even IPv4-Hosts get an IPv6 address.
When I then get home into a full Dual-Stack WiFi, Nextcloud will forever keep trying to connect to the NAT64 address, which obviously fails.

Likewise, when I switch from WiFi to Mobile Data, it'll keep trying to use the real IPv4 address, which fails on the IPv6/NAT64-Only mobile network.

This still not being fixed is a massive shame, and slowly making me look for alternatives.

**Comment by larena1** [comment]
@BtbN

https://github.com/200Puls/android-library/blob/c333b824b42109c6e07d9d9c46f9b7d3045b2ebc/src/main/java/com/nextcloud/common/IPV6PreferringDNS.java#L23

Might be due to the previously resolved IP indefinitely being in the cache there. Should work when you force close the app but less than an ideal solution either

**Comment by BtbN** [comment]
I've tried force closing it, obviously. So far only a reboot has been able to resolve it.
Until I switch network again.

It's also only Nextcloud having that issue, nothing else.

**Comment by larena1** [comment]
Are you stopping the app from settings or just closing from recents? Stopping should work at it'll terminate the app and all services thus the cache will be empty on next start

**Comment by mburnicki** [comment]
> This still not being fixed is a massive shame, and slowly making me look for alternatives.

I absolutely agree. I have several apps on the same smartphone which access the server on my home network through the router:
K-9 Mail and FairEmail for email, DAVx5 which successfully contacts the nextcloud server which isn't reachable for the Nextcloud app, and even SyncThinkFork, which I'm currently using to get the file synchronization which the Nextcloud app is unable to achieve. :-(

Nextcloud is the only app that is unable to contact device on my home network.

**Comment by larena1** [comment]
@AndyScherzinger @tobiasKaminsky I see you've already posted here in 2020. Is there any fix planned for this maybe?

**Comment by oddstr13** [comment]
I can't speak for the developers of Nextcloud, but the way most community driven open source project works is that issues are prioritized based on personal interest, available time, and applicable skill.

This issue likely hasn't been fixed because none of the active project devs have had any significant issues with it, and nobody from the wider community has stepped up.

I personally have no motivation to look into this issue right now, because what caused me to hit this issue was the fact that the IPv6 address had changed since I set up the server, and fixing that made it go away… I have plenty of other projects I'm more motivated to work on ;)

There are currently 73 open pull-requests, and 890 open issues. 73 pull-requests have been merged the past month, and 56 issues closed.

Try not being too demanding when interacting with open source developers, as this can be a significant drain on the energy that would otherwise be put towards fixing issues and implementing improvements and new features, and could cause people to more easily burn out on a project.

If you feel particularly strongly about getting an issue fixed, you should look into;
- Understanding exactly what's happening
- Why that is a problem
- What are the options for changing this behavior for the better
- How it could be implemented

And then either provide this information in a clear way in the relevant issue,
Or preferably, implement the changes, submit a PR, and help fix the problems the maintainers may spot in your code.

*Anyone* can do this, no matter their prior level of programming or computer expertise, the only difference is the time and effort it takes to get up to speed, learn the required concepts/skills, and correctly implement it.

For some, this could be hours/days, for others it could be weeks/months. How motivated are *you* to go fix this particular issue?

This is the main reason for why I love open-source: If it's broken, and annoys me enough, I *can* go fix it, both for myself and others.

**Comment by AlvaroBrey** [comment]
Anyone willing to test the QA apk in [this comment](https://github.com/nextcloud/android/pull/9685#issuecomment-1010906742)? 

On top of what @flob82 said, this particular issue is slightly harder than usual to reproduce and test. For example, I don't have working IPv6, so there's not much I can do. If anyone can suggest an easy way to reproduce (other than "get your IPv6 working and break the server") that would be great.

**Comment by larena1** [comment]
@AlvaroBrey You don't actually need to have IPv6 at home. All you need is a server with an AAAA record and try to connect to that from your IPv4 home. The app will pick the IPv6 address because that's preferred and fail to connect.

I tried your APK but it won't work. I insert my server's address but it says host not found when connecting from and IPv4 only network. Connecting from IPv6 enabled mobile network does work though.

**Comment by larena1** [comment]
Same error on onboarding screen unfortunately. Works on IPv6 network, does not fall back on IPv4 only network.

**Comment by AlvaroBrey** [comment]
Please test [this last one](https://github.com/nextcloud/android/pull/9685#issuecomment-1011900034) if possible. If this one doesn't work I'll need to do some more work with my network. However I have high hopes for this APK.

> All you need is a server with an AAAA record and try to connect to that from your IPv4 home. The app will pick the IPv6 address because that's preferred and fail to connect.

Unfortunately that isn't the case. As I have no IPv6 connectivity at home, my testing devices seem to be ignoring the AAAA record entirely.

**Comment by laf0rge** [comment]
> Unfortunately that isn't the case. As I have no IPv6 connectivity at home, my testing devices seem to be ignoring the AAAA record entirely.

Yes, that is clear.  If you do not even have any router that assigns IPv6 addresses to your device, your device will not have an IPv6 default route, and hence it will not make IPv6 connections at all.

What you need is a local router (can be a random linux, openwrt, ... box) on the same network segment that provides IPv6 addresses via statless auto-configuration (router advertisements).  That way your android device will have both an IPv4 and an IPv6 default route, but only the IPv4 route will be working while he IPv6 one is interrupted as you have no IPv6 uplink.

The same might also be possible toreach with a DHCPv6 server, but for sure it works with IPv6 stateless auto-cofiguratiom

**Comment by mburnicki** [comment]
Works for me, too!
Thanks!

**Comment by larena1** [comment]
It seems as if the app will only use ipv4 now despite proper ipv6 network. It's still better than before as it'll at least work now in an ipv4 only network.

And I think if it used ipv6 to connect and cached that, it might fail when switching to an ipv4 only network as the IPv6 address is still in the cache and is never purged?

**Comment by AlvaroBrey** [comment]
> It seems as if the app will only use ipv4 now despite proper ipv6 network. It's still better than before as it'll at least work now in an ipv4 only network.
> 
> And I think if it used ipv6 to connect and cached that, it might fail when switching to an ipv4 only network as the IPv6 address is still in the cache and is never purged?

You can see the changes in https://github.com/nextcloud/android-library/pull/793. The app still tries IPv6 first, and then if a timeout, connect exception or 5xx error is received on the IPv6 connection, the DNS preference is changed to IPv4. This is cached until the app dies (reboot, close from recents, etc).

**Comment by larena1** [comment]
Tried again and you're right. On an ipv6 network it'll connect via ipv6. The app probably had the preference still cached because I didn't force stop it.

It'll also fall back to ipv4 when I join an ipv4 only network and connected via ipv6 before. It will though never use ipv6 again even when it's available while the app is still running but I can live with that.

**Comment by AlvaroBrey** [comment]
> It will though never use ipv6 again even when it's available while the app is still running but I can live with that.

Checking both IPs too frequently would result in too much overhead, I think. However, it may be worthwhile to implement a cache timeout (1 hour? 4 hours? 1 day?) so that the cache doesn't live forever as long as the app is open.

**Comment by laf0rge** [comment]
I don't think there is a need to create some kind of custom cache etc. but simlpy align with what everyone else does.  I'm very surprised that Android doesn't take care of this in some generic way, but rather places the burden on each and every application.

In general, there is https://en.wikipedia.org/wiki/Happy_Eyeballs as well as RFC6555 (https://datatracker.ietf.org/doc/html/rfc6555) and RFC8305 (https://datatracker.ietf.org/doc/html/rfc8305) as the kind of reference on the expected behavior.

**Comment by BtbN** [comment]
Does this change also address my odd case of NAT64, where the DNS Server on Mobile Network returns a different (IPv6-Only, but only works on that mobile network) address for my IPv4-Only Server than the server on any regular WiFi will?
If I read the code correctly, it'll still infinitely cache that result, and since there's nothing to re-sort(DNS returns only one address) the preference-swap will not do anything for it.

The correct way to deal with that would probably be to monitor for `android.net.conn.CONNECTIVITY_CHANGE` and `android.net.wifi.STATE_CHANGE` and evict the cache when they fire.

I'm also surprised there is no OS-Wide DNS Cache that deals with this kind of stuff.

**Comment by larena1** [comment]
https://daniel.haxx.se/blog/2020/03/16/curl-ootw-happy-eyeballs-timeout/

Some details about how happy eyeballs is implemented in curl.

https://github.com/square/okhttp/issues/506

Okhttp currently does not seem to support it but coincidentally it seems there's currently work being done to support that

https://github.com/square/okhttp/pull/7009

**Comment by AlvaroBrey** [comment]
> I don't think there is a need to create some kind of custom cache etc. but simlpy align with what everyone else does. I'm very surprised that Android doesn't take care of this in some generic way, but rather places the burden on each and every application.
> 
> In general, there is https://en.wikipedia.org/wiki/Happy_Eyeballs as well as RFC6555 (https://datatracker.ietf.org/doc/html/rfc6555) and RFC8305 (https://datatracker.ietf.org/doc/html/rfc8305) as the kind of reference on the expected behavior.

**Comment by AlvaroBrey** [comment]
@BtbN would you mind testing [this newer APK](https://github.com/nextcloud/android/pull/9685#issuecomment-1015208815)? This one should fix connectivity with your quirky setup too

**Comment by BtbN** [comment]
> @BtbN would you mind testing [this newer APK](https://github.com/nextcloud/android/pull/9685#issuecomment-1015208815)? This one should fix connectivity with your quirky setup too

Yep, that has done the trick.
I tried all combination of switching from Wifi to mobile, back, and the other way around, and never ran into a situation where it couldn't connect.
