### ISSUE TITLE
Notifications has no content

### ISSUE THREAD

**Issue by fzirker** [nextcloud/android#7897]
### Steps to reproduce
1. Alice uses the nextcloud app
2. Login to a seperate user account in nextcloud web at user Bob
3. Bob shares a folder or a file with user Alice (direct share)

### Expected behaviour
- Alice gets a notification "Bob shared the folder test with you" (ore something likely)
- The Notification has a Nextcloud icon
- Only one notification
- Clicking on the notifications opens the app and shows the containing folder

### Actual behaviour
<img src="https://user-images.githubusercontent.com/2885066/105875127-b308e000-5ffd-11eb-8bae-6d2dd6a2b06a.jpg" width="500">

- andorid default icon
- no text
- two notifications at the same time
- clicking on the notification brings me to the containing folder. Works as expected.

### Environment data
Android version: 8.0.0
Device model: Samsung S7
Stock or customized system: stock
Nextcloud app version: 3.14.3
Nextcloud server version: 20.0.5

**Comment by cieska** [comment]
Same here.
* Notification icon in the top bar has no actual iron, just a large squarish dot. 
* notification messages has no valuable info.
* when clicking on notification, NC app opens in last used folder. 
* when opening Notification section on app, there is no info. 
![Screenshot_20210126-213531](https://user-images.githubusercontent.com/41318524/105955892-e59ef100-606e-11eb-8ce4-8afd85a0785e.jpg)
![Screenshot_20210126-213548](https://user-images.githubusercontent.com/41318524/105955894-e6378780-606e-11eb-983e-f0aad5eb8c14.jpg)

**Comment by fzirker** [comment]
Today i checkted this agai and it is fixed for me. @cieska can you confirm?

I installed the server verstion 20.0.7 and android client 3.15.0.

**Comment by tobiasKaminsky** [comment]
This should be fixed with 3.15.0.

**Comment by palight** [comment]
On my device it's still here with server versioj 20.0.0.8 and android version 3.15.

**Comment by tobiasKaminsky** [comment]
Can you try it again? I changed something on our google app settings.

**Comment by palight** [comment]
Hello, I just tested after reseting my app (data and cache) and revoking the autorisations for my device. When I register the device again, problem is still there.
