### ISSUE TITLE
File/folder sharing : comments and e-mail notifications

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/android#9689]
Hello,

### Is your feature request related to a problem? Please describe.
When I share a folder or file with my Android client application, I noticed that adding a comment is mandatory. I don't think this is useful (and even annoying in some cases). What's also annoying is that it sends two email notifications to the recipient after clicking on the share button, but I think there should only be one email in this case (it should indicate the name of the shared file or folder, as well as the comment if there is one).

### Describe the solution you'd like
- no obligation to comment
- one email notification when there is a comment

### Describe alternatives you've considered
No idea.

### Additional context
Don't hesitate to ask me for details and screenshots. 

I remain at your disposal.

Best regards,

Jérôme

**Comment by AlvaroBrey** [comment]
Duplicate of #9308

**Comment by AlvaroBrey** [comment]
For reference, this was a bug in 3.18.0 and should be fixed in 3.18.1.

**Comment by Jerome-Herbinet** [comment]
Hi again,
I have recently updated my Android Nextcloud client and i have noticed that the comment texteara is no longer mandatory (good news). 
However, as mentioned in my initial report, there is another problem that persists: After several tests, I still see that two emails are sent (when I have put a comment), which is not interesting (and may confuse the recipient). Should I open another issue? ... or can I reopen this one ?
Thanks in advance.
Jérôme

**Comment by AlvaroBrey** [comment]
> Hi again, I have recently updated my Android Nextcloud client (3.18.1 now) and i have noticed that the comment texteara is no longer mandatory (good news). However, as mentioned in my initial report, there is another problem that persists: After several tests, I still see that two emails are sent (when I have put a comment), which is not interesting (and may confuse the recipient). Should I open another issue? ... or can I reopen this one ? Thanks in advance. Jérôme

AFAIK this is a server limitation. @tobiasKaminsky might know more

**Comment by Jerome-Herbinet** [comment]
Hello @tobiasKaminsky , 
Can you confirm this and tell me some details that would allow me to fix the problem on my instance (what settings, if any) ?
Thanks in advance.
Jérôme

**Comment by tobiasKaminsky** [comment]
Right now there is one mail for creating the share, and the other for (every) comment update.
This can only be changed for NC24, when we are able to create a new share directly with a comment included.
